### ISSUE TITLE
ios8.0下spritejs对象为undefined 导致页面白屏

### ISSUE THREAD

**Issue by veeking** [spritejs/spritejs#103]
ios8.0下spritejs对象为undefined, 浏览器直接调用window下没有spritejs对象。
spritejs版本：2.27.18（尝试在2.5.1版本下是正常）
ios版本信息：
![image](https://user-images.githubusercontent.com/5451901/59414436-1972c780-8df4-11e9-881c-719e22e09e6e.png)

**Comment by akira-cn** [comment]
see #105
