### ISSUE TITLE
官方文档自定义元素组件章节演示运行报错

### ISSUE THREAD

**Issue by veeking** [spritejs/spritejs#105]
在官方自定义组件元素的示例代码中，使用extend继承Sprite就会报错
**Uncaught TypeError: Class constructor Sprite cannot be invoked without 'new'**

是官方文档老旧了？？

**Comment by akira-cn** [comment]
官方文档中的spritejs是自动更新到最新版本的。

你的报错是build的问题，你是使用webpack还是其他构建工具？

**Comment by veeking** [comment]
> 官方文档中的spritejs是自动更新到最新版本的。
> 
> 你的报错是build的问题，你是使用webpack还是其他构建工具？

用的webpack， 给你贴下基本配置， 您看看是不是有配置不对？
webpack
![image](https://user-images.githubusercontent.com/5451901/59614529-87e8ba00-9153-11e9-834d-fd6cc3545c59.png)
babelrc
![image](https://user-images.githubusercontent.com/5451901/59614483-756e8080-9153-11e9-9c60-741a683db698.png)

**Comment by akira-cn** [comment]
因为你把 node_modules 给 exclude 掉了，你设置一下 

```js
alias: {
    spritejs: 'spritejs/dist/spritejs.js',
}
```

这样应该就可以了

**Comment by akira-cn** [comment]
主要是因为我package.json的main里面设置的是lib/index.js，这是我的babel配置编译到es5的版本，可能是因为这个问题导致的。

**Comment by veeking** [comment]
> 主要是因为我package.json的main里面设置的是lib/index.js，这是我的babel配置编译到es5的版本，可能是因为这个问题导致的。

太谢谢了，加上spritejs别名指向就可以了，原因是不是默认import的是lib/index.js版本 导致了extend的报错？

**Comment by akira-cn** [comment]
是的，lib/index.js应该是babel编译的，那个转es-module导致有问题，我下一次更新的时候把main配置改一下，改成dist下的文件应该就好了

**Comment by veeking** [comment]
> 是的，lib/index.js应该是babel编译的，那个转es-module导致有问题，我下一次更新的时候把main配置改一下，改成dist下的文件应该就好了

好的谢谢了。最后有个小问题就是ios8.0上好像一直白屏（spritejs一直undefined），我简单调试了下，直接在浏览器引入spritejs，ios8.0下没有spritejs这个对象，似乎没有导出，ios8.0（iphone5s）是不是有什么写法不兼容导致没有成功导出对象？

**Comment by akira-cn** [comment]
ios8可能要引一下es5-shim？我不确定，因为我没有测试环境，你可以试一下。

**Comment by veeking** [comment]
> ios8可能要引一下es5-shim？我不确定，因为我没有测试环境，你可以试一下。

行好的 我试试看

**Comment by akira-cn** [comment]
你好，我测了一下，iOS8因为不支持Symbol，要引入 [babel-polyfill](https://cdn.baomitu.com/babel-polyfill)

这样就行了

**Comment by veeking** [comment]
> [babel-polyfill](https://cdn.baomitu.com/babel-polyfill)

确实，引入 babel-polyfill 后ios8成功显示了，缺点是文件babel转码后总体大小增大了100kb左右 哈哈XD

**Comment by veeking** [comment]
> 你好，我测了一下，iOS8因为不支持Symbol，要引入 [babel-polyfill](https://cdn.baomitu.com/babel-polyfill)
> 
> 这样就行了

确实，引入 babel-polyfill 后ios8成功显示了，缺点是文件babel转码后总体大小增大了100kb左右 哈哈XD😆

**Comment by peade** [comment]
> 是的，lib/index.js应该是babel编译的，那个转es-module导致有问题，我下一次更新的时候把main配置改一下，改成dist下的文件应该就好了

我也出现这个问题了。
我是使用webpack打包的

直接copy了这个页面的代码
http://spritejs.org/demo/#events
在代码的最前面，我加了一行import引入spritejs
`import * as spritejs from 'spritejs'`
其他代码没调整
最后报的是下面这样的错
> 03demo.js:3 Uncaught (in promise) TypeError: Class constructor Label cannot be invoked without 'new'
>     at new KeyButton (03demo.js:3)

这个需要怎么解决？
