### ISSUE TITLE
这个库编译完是真的好多坑...

### ISSUE THREAD

**Issue by DricHao** [spritejs/spritejs#106]
TypeError: Cannot convert undefined or null to object

**Comment by akira-cn** [comment]
你好，麻烦提供具体的编译配置。
目前有多个项目都是依赖spritejs正常编译的，未发现有不能编译的情况。

**Comment by DricHao** [comment]
> 你好，麻烦提供具体的编译配置和运行环境。
> 目前有多个项目都是依赖spritejs正常编译的，未发现有不能编译以及编译完不能运行的情况。
> 
> 另外做这个库的初衷主要是做跨平台的数据可视化的，因此并未考虑IE浏览器和一些比较早的浏览器版本，运行在这些浏览器上可能会有兼容问题，不过有些问题可以通过引入babel-polyfill解决。

好的，谢谢回复。 我关了
