### ISSUE TITLE
v2.29.2版本怎么没有v2.27.21稳定呢？

### ISSUE THREAD

**Issue by veeking** [spritejs/spritejs#109]
v2.29.2版本是不是很多东西改了？目前我发现的问题：
1、zIndex失效
2、touch事件获取pageX似乎被取消换成别的参数

**Comment by akira-cn** [comment]
稍等我看一下，1不应该有问题啊，2的touch事件一直并没有推荐使用pageX，一直是用offsetX和layerX的

**Comment by akira-cn** [comment]
1的问题，我修复了，你更新到2.29.3就行了
