### ISSUE TITLE
播放音频，需要怎么处理？

### ISSUE THREAD

**Issue by peade** [spritejs/spritejs#111]
播放动画，经常需要播放音乐什么的。我看文档里，没有这块的处理，目前是不是得用外部的audio播放来处理？有更好的处理方式么？
播放音频的功能，方便集成到里面么？

**Comment by akira-cn** [comment]
audio有不少好用的第三方库，直接使用外部的库就好了，spritejs本身没有集成这个

**Comment by fengdi** [comment]
比如 howler
