### ISSUE TITLE
spritejs.esm.js IOS > 10 无法导入

### ISSUE THREAD

**Issue by aolsx** [spritejs/spritejs#114]
spritejs.esm.js IOS > 10 无法导入 
新修改的 spritejs.js 可导入
折腾一下午 win 装了一堆工具，总算能调试 IOS真机，看到了Bug信息。
您看是否也能更新下 spritejs.esm.js 否则一升级又回去了

**Comment by akira-cn** [comment]
不是无法导入，而是spritejs.esm.js在iOS较早版本时需要编译成ES5，现在默认是es6
可以用两个方法，如果使用webpack，可以配置 `alias: {'spritejs': 'spritejs/dist/spritejs.js'}`
或者可以在babel-loader的配置中增加 `includes: ['node_modules/spritejs']`

**Comment by aolsx** [comment]
原来如此，非常感谢！
