### ISSUE TITLE
请问spritejs怎么获取画板是否绘制完成

### ISSUE THREAD

**Issue by coderliwenjie** [spritejs/spritejs#116]

**Comment by akira-cn** [comment]
用 `await layer.prepareRenderer()` 可以判断当前帧绘制完成

**Comment by coderliwenjie** [comment]
@akira-cn 使用时提示没有这个方法，文档里面也没有介绍

**Comment by coderliwenjie** [comment]
找到了是layer.prepareRender()

**Comment by akira-cn** [comment]
嗯嗯，是的，回头我们在文档里面再特别说明一下

**Comment by coderliwenjie** [comment]
@akira-cn 请问一个问题，我在vue里面的mounted生命周期钩子调用layer.prepareRender()，相等到canvas绘制完成，生成快照，但是每次都是黑的，prepareRender好像没用，没有绘制完成，使用setTimeout延迟200ms生成快照，canvas就绘制好了，求解答

**Comment by akira-cn** [comment]
这是因为你有一些异步的图片吧，prepareRender()只是当前帧绘制完成，但是如果sprite的图片是没有预加载的，那么有些元素是绘制不出来的，必须等待图片加载完成。

**Comment by akira-cn** [comment]
另外，快照的话，你可以直接用[这个api](http://spritejs.org/#/zh-cn/guide/snapshot)，不过图片一样要预加载或者等待加载完成。

**Comment by coderliwenjie** [comment]
我把所有要绘制的图片先预加载了一遍，加载完成后再绘图，然后生存快照，还是黑的

**Comment by akira-cn** [comment]
你把代码贴上来看一下吧

**Comment by coderliwenjie** [comment]
` preloadImages(images).then((res) => {
      editable.groups.forEach(async (group, idx, arr) => {
        const { Scene, Sprite, Label, Group } = spritejs
        const scene = new Scene(`#canvas-${idx}`, {
          viewport: [viewWidth, viewHeight],
          resolution: [viewWidth, viewHeight],
          displayRatio: '2vw'
        })
        console.log('ss')
        const layer = scene.layer()
        group.layers.forEach(item => {
        /**
         * @param positionX 图层x坐标
         * @param positionY 图层y坐标
         * @param textAttrs 文字属性
         * @param textFeature 文字图层特性
        */
          const positionX = item.transform.dx - item.transform.ax * item.transform.sx
          const positionY = item.transform.dy - item.transform.ay * item.transform.sy
          if (item.type === 1) {
            const textAttrs = getTextAttrs(source.texts, item.srcId)
            const textFeature = transFeature(textAttrs.flags, item.type)
            let text = ''
            // 判断是否为微信
            if (textFeature.textIsWechatNickname) {
              text = this.userInfo.name
            } else {
              text = textAttrs.text.zh
            }
            // 加载字体
            loadFont(text, textAttrs.typeface.name, this.appToken, item.uid)
            // 横排文字竖排文字分别处理
            if (textFeature.textIsLayoutVertical) {
            /**
             * @param hAlign 文字水平布局
             * @param vAlign 文字垂直布局
            */
              let layout = new Group()
              const hAlign = ['center', 'flex-start', 'flex-end']
              const vAlign = ['center', 'flex-start', 'flex-end']
              layout.attr({
                display: 'flex',
                flexDirection: 'column',
                justifyContent: vAlign[textAttrs.vAlign],
                alignItems: hAlign[textAttrs.hAlign],
                pos: [(positionX + textAttrs.bounds.x) * scale, (positionY + textAttrs.bounds.y) * scale],
                width: textAttrs.bounds.w * scale,
                height: textAttrs.bounds.h * scale,
                border: {
                  width: 1,
                  style: 'solid',
                  color: '#00b6fd'
                },
                transform: {
                  rotate: `${item.transform.angle}deg`,
                  scale: [item.transform.sx, item.transform.sy]
                }
              })
              text.split('').forEach(character => {
                const label = new Label(character)
                label.attr({
                  fillColor: textAttrs.color,
                  lineHeight: textAttrs.typeface.size * scale,
                  font: `${textAttrs.typeface.size * scale}px "font-${item.uid}"`
                })
                layout.append(label)
              })
              layout.addEventListener('click', (e) => {
                e.stopDispatch()
                this.textEdit()
              })
              layer.append(layout)
            } else {
            /**
             * @param hAlign 文字水平布局
             * @param lineHeight 用lineHeight控制文本垂直布局
            */
              const hAlign = ['center', 'left', 'top']
              const lineHeight = [textAttrs.bounds.h * scale, textAttrs.bounds.h * scale - textAttrs.typeface.size * scale / 2, textAttrs.bounds.h * scale + textAttrs.typeface.size * scale / 2]
              const label = new Label(text)
              label.attr({
                pos: [(positionX + textAttrs.bounds.x) * scale, (positionY + textAttrs.bounds.y) * scale],
                width: textAttrs.bounds.w * scale,
                height: textAttrs.bounds.h * scale,
                lineHeight: lineHeight[textAttrs.vAlign],
                textAlign: hAlign[textAttrs.hAlign],
                fillColor: textAttrs.color,
                font: `${textAttrs.typeface.size * scale}px "font-${item.uid}"`,
                border: {
                  width: 1,
                  style: 'solid',
                  color: '#00b6fd'
                },
                transform: {
                  rotate: `${item.transform.angle}deg`,
                  scale: [item.transform.sx, item.transform.sy]
                }
              })
              layer.append(label)
            }
          } else if (item.type === 2) {
          /**
           * @param imgFeature 图片特性
           * @param imgUrl 图片链接
          */
            const imgFeature = transFeature(getSourceFlag(source.images, item.srcId), item.type)
            let imgUrl = getImgUrl(metadata.images, item.srcId)
            // 没有图片链接添加默认图片
            if (!imgUrl) {
              if (imgFeature.sourceIsWechatPortrait) {
                imgUrl = this.userInfo.avatar
              } else {
                imgUrl = 'https://img-dpy.bhbcdn.com/cv-img_841b15_1563158893467.jpg'
              }
            }
            const sprite = new Sprite()
            // group限制在图片变换时超出区域隐藏
            const group = new Group()
            group.attr({
              pos: [positionX * scale, positionY * scale],
              width: item.width * scale * item.transform.sx,
              height: item.height * scale * item.transform.sy
            })
            sprite.attr({
              width: item.width * scale,
              height: item.height * scale,
              textures: [{
                src: imgUrl
              }],
              transform: {
                rotate: `${item.transform.angle}deg`,
                scale: [item.transform.sx, item.transform.sy]
              }
            })
            group.append(sprite)
            layer.append(group)
            if (imgFeature.sourceIsImportedImage) {
              imgLayers.push(group)
              sprite.on('click', (e) => {
                const input = document.getElementById('file')
                input.addEventListener('change', (e) => {
                  this.fileChange(e, sprite, scene)
                })
                input.click()
              })
            }
          }
        })
        const snapshot = await generateSnapshots(scene)
        snapshots.push(snapshot)
        if (idx === editable.groups.length - 1) {
          this.generateSnapshots(snapshots)
        }
      })
    })`

**Comment by coderliwenjie** [comment]
preloadImages(images).then((res) => {
      editable.groups.forEach(async (group, idx, arr) => {
        const { Scene, Sprite, Label, Group } = spritejs
        const scene = new Scene(`#canvas-${idx}`, {
          viewport: [viewWidth, viewHeight],
          resolution: [viewWidth, viewHeight],
          displayRatio: '2vw'
        })
        console.log('ss')
        const layer = scene.layer()
        group.layers.forEach(item => {
        /**
         * @param positionX 图层x坐标
         * @param positionY 图层y坐标
         * @param textAttrs 文字属性
         * @param textFeature 文字图层特性
        */
          const positionX = item.transform.dx - item.transform.ax * item.transform.sx
          const positionY = item.transform.dy - item.transform.ay * item.transform.sy
          if (item.type === 1) {
            const textAttrs = getTextAttrs(source.texts, item.srcId)
            const textFeature = transFeature(textAttrs.flags, item.type)
            let text = ''
            // 判断是否为微信
            if (textFeature.textIsWechatNickname) {
              text = this.userInfo.name
            } else {
              text = textAttrs.text.zh
            }
            // 加载字体
            loadFont(text, textAttrs.typeface.name, this.appToken, item.uid)
            // 横排文字竖排文字分别处理
            if (textFeature.textIsLayoutVertical) {
            /**
             * @param hAlign 文字水平布局
             * @param vAlign 文字垂直布局
            */
              let layout = new Group()
              const hAlign = ['center', 'flex-start', 'flex-end']
              const vAlign = ['center', 'flex-start', 'flex-end']
              layout.attr({
                display: 'flex',
                flexDirection: 'column',
                justifyContent: vAlign[textAttrs.vAlign],
                alignItems: hAlign[textAttrs.hAlign],
                pos: [(positionX + textAttrs.bounds.x) * scale, (positionY + textAttrs.bounds.y) * scale],
                width: textAttrs.bounds.w * scale,
                height: textAttrs.bounds.h * scale,
                border: {
                  width: 1,
                  style: 'solid',
                  color: '#00b6fd'
                },
                transform: {
                  rotate: `${item.transform.angle}deg`,
                  scale: [item.transform.sx, item.transform.sy]
                }
              })
              text.split('').forEach(character => {
                const label = new Label(character)
                label.attr({
                  fillColor: textAttrs.color,
                  lineHeight: textAttrs.typeface.size * scale,
                  font: `${textAttrs.typeface.size * scale}px "font-${item.uid}"`
                })
                layout.append(label)
              })
              layout.addEventListener('click', (e) => {
                e.stopDispatch()
                this.textEdit()
              })
              layer.append(layout)
            } else {
            /**
             * @param hAlign 文字水平布局
             * @param lineHeight 用lineHeight控制文本垂直布局
            */
              const hAlign = ['center', 'left', 'top']
              const lineHeight = [textAttrs.bounds.h * scale, textAttrs.bounds.h * scale - textAttrs.typeface.size * scale / 2, textAttrs.bounds.h * scale + textAttrs.typeface.size * scale / 2]
              const label = new Label(text)
              label.attr({
                pos: [(positionX + textAttrs.bounds.x) * scale, (positionY + textAttrs.bounds.y) * scale],
                width: textAttrs.bounds.w * scale,
                height: textAttrs.bounds.h * scale,
                lineHeight: lineHeight[textAttrs.vAlign],
                textAlign: hAlign[textAttrs.hAlign],
                fillColor: textAttrs.color,
                font: `${textAttrs.typeface.size * scale}px "font-${item.uid}"`,
                border: {
                  width: 1,
                  style: 'solid',
                  color: '#00b6fd'
                },
                transform: {
                  rotate: `${item.transform.angle}deg`,
                  scale: [item.transform.sx, item.transform.sy]
                }
              })
              layer.append(label)
            }
          } else if (item.type === 2) {
          /**
           * @param imgFeature 图片特性
           * @param imgUrl 图片链接
          */
            const imgFeature = transFeature(getSourceFlag(source.images, item.srcId), item.type)
            let imgUrl = getImgUrl(metadata.images, item.srcId)
            // 没有图片链接添加默认图片
            if (!imgUrl) {
              if (imgFeature.sourceIsWechatPortrait) {
                imgUrl = this.userInfo.avatar
              } else {
                imgUrl = 'https://img-dpy.bhbcdn.com/cv-img_841b15_1563158893467.jpg'
              }
            }
            const sprite = new Sprite()
            // group限制在图片变换时超出区域隐藏
            const group = new Group()
            group.attr({
              pos: [positionX * scale, positionY * scale],
              width: item.width * scale * item.transform.sx,
              height: item.height * scale * item.transform.sy
            })
            sprite.attr({
              width: item.width * scale,
              height: item.height * scale,
              textures: [{
                src: imgUrl
              }],
              transform: {
                rotate: `${item.transform.angle}deg`,
                scale: [item.transform.sx, item.transform.sy]
              }
            })
            group.append(sprite)
            layer.append(group)
            if (imgFeature.sourceIsImportedImage) {
              imgLayers.push(group)
              sprite.on('click', (e) => {
                const input = document.getElementById('file')
                input.addEventListener('change', (e) => {
                  this.fileChange(e, sprite, scene)
                })
                input.click()
              })
            }
          }
        })
        const snapshot = await generateSnapshots(scene)
        snapshots.push(snapshot)
        if (idx === editable.groups.length - 1) {
          this.generateSnapshots(snapshots)
        }
      })
    })

**Comment by coderliwenjie** [comment]
preloadImages(images).then((res) => {
      editable.groups.forEach(async (group, idx, arr) => {
        const { Scene, Sprite, Label, Group } = spritejs
        const scene = new Scene(`#canvas-${idx}`, {
          viewport: [viewWidth, viewHeight],
          resolution: [viewWidth, viewHeight],
          displayRatio: '2vw'
        })
        console.log('ss')
        const layer = scene.layer()
        group.layers.forEach(item => {
        /**
         * @param positionX 图层x坐标
         * @param positionY 图层y坐标
         * @param textAttrs 文字属性
         * @param textFeature 文字图层特性
        */
          const positionX = item.transform.dx - item.transform.ax * item.transform.sx
          const positionY = item.transform.dy - item.transform.ay * item.transform.sy
          if (item.type === 1) {
            const textAttrs = getTextAttrs(source.texts, item.srcId)
            const textFeature = transFeature(textAttrs.flags, item.type)
            let text = ''
            // 判断是否为微信
            if (textFeature.textIsWechatNickname) {
              text = this.userInfo.name
            } else {
              text = textAttrs.text.zh
            }
            // 加载字体
            loadFont(text, textAttrs.typeface.name, this.appToken, item.uid)
            // 横排文字竖排文字分别处理
            if (textFeature.textIsLayoutVertical) {
            /**
             * @param hAlign 文字水平布局
             * @param vAlign 文字垂直布局
            */
              let layout = new Group()
              const hAlign = ['center', 'flex-start', 'flex-end']
              const vAlign = ['center', 'flex-start', 'flex-end']
              layout.attr({
                display: 'flex',
                flexDirection: 'column',
                justifyContent: vAlign[textAttrs.vAlign],
                alignItems: hAlign[textAttrs.hAlign],
                pos: [(positionX + textAttrs.bounds.x) * scale, (positionY + textAttrs.bounds.y) * scale],
                width: textAttrs.bounds.w * scale,
                height: textAttrs.bounds.h * scale,
                border: {
                  width: 1,
                  style: 'solid',
                  color: '#00b6fd'
                },
                transform: {
                  rotate: `${item.transform.angle}deg`,
                  scale: [item.transform.sx, item.transform.sy]
                }
              })
              text.split('').forEach(character => {
                const label = new Label(character)
                label.attr({
                  fillColor: textAttrs.color,
                  lineHeight: textAttrs.typeface.size * scale,
                  font: `${textAttrs.typeface.size * scale}px "font-${item.uid}"`
                })
                layout.append(label)
              })
              layout.addEventListener('click', (e) => {
                e.stopDispatch()
                this.textEdit()
              })
              layer.append(layout)
            } else {
            /**
             * @param hAlign 文字水平布局
             * @param lineHeight 用lineHeight控制文本垂直布局
            */
              const hAlign = ['center', 'left', 'top']
              const lineHeight = [textAttrs.bounds.h * scale, textAttrs.bounds.h * scale - textAttrs.typeface.size * scale / 2, textAttrs.bounds.h * scale + textAttrs.typeface.size * scale / 2]
              const label = new Label(text)
              label.attr({
                pos: [(positionX + textAttrs.bounds.x) * scale, (positionY + textAttrs.bounds.y) * scale],
                width: textAttrs.bounds.w * scale,
                height: textAttrs.bounds.h * scale,
                lineHeight: lineHeight[textAttrs.vAlign],
                textAlign: hAlign[textAttrs.hAlign],
                fillColor: textAttrs.color,
                font: `${textAttrs.typeface.size * scale}px "font-${item.uid}"`,
                border: {
                  width: 1,
                  style: 'solid',
                  color: '#00b6fd'
                },
                transform: {
                  rotate: `${item.transform.angle}deg`,
                  scale: [item.transform.sx, item.transform.sy]
                }
              })
              layer.append(label)
            }
          } else if (item.type === 2) {
          /**
           * @param imgFeature 图片特性
           * @param imgUrl 图片链接
          */
            const imgFeature = transFeature(getSourceFlag(source.images, item.srcId), item.type)
            let imgUrl = getImgUrl(metadata.images, item.srcId)
            // 没有图片链接添加默认图片
            if (!imgUrl) {
              if (imgFeature.sourceIsWechatPortrait) {
                imgUrl = this.userInfo.avatar
              } else {
                imgUrl = 'https://img-dpy.bhbcdn.com/cv-img_841b15_1563158893467.jpg'
              }
            }
            const sprite = new Sprite()
            // group限制在图片变换时超出区域隐藏
            const group = new Group()
            group.attr({
              pos: [positionX * scale, positionY * scale],
              width: item.width * scale * item.transform.sx,
              height: item.height * scale * item.transform.sy
            })
            sprite.attr({
              width: item.width * scale,
              height: item.height * scale,
              textures: [{
                src: imgUrl
              }],
              transform: {
                rotate: `${item.transform.angle}deg`,
                scale: [item.transform.sx, item.transform.sy]
              }
            })
            group.append(sprite)
            layer.append(group)
            if (imgFeature.sourceIsImportedImage) {
              imgLayers.push(group)
              sprite.on('click', (e) => {
                const input = document.getElementById('file')
                input.addEventListener('change', (e) => {
                  this.fileChange(e, sprite, scene)
                })
                input.click()
              })
            }
          }
        })
        const snapshot = await generateSnapshots(scene)
        snapshots.push(snapshot)
        if (idx === editable.groups.length - 1) {
          this.generateSnapshots(snapshots)
        }
      })
    })

**Comment by coderliwenjie** [comment]
请问我这代码贴的有问题吗？

**Comment by akira-cn** [comment]
```js
sprite.attr({
          width: item.width * scale,
          height: item.height * scale,
          textures: [{
            src: imgUrl
          }],
```

你这个还是没有预加载图片，你要用spritejs提供的资源预加载，[文档在这里](http://spritejs.org/#/zh-cn/guide/resource)

不要直接用url设置textures，否则的话还是要下载这个图片然后才能完成渲染。

**Comment by coderliwenjie** [comment]
感谢提点，之前理解错了，自己对图片做了个预加载，现在按照你提示的解决了
