### ISSUE TITLE
在group上做scale，会导致group里面的path糊掉

### ISSUE THREAD

**Issue by RyanZhu1024** [spritejs/spritejs#118]
https://codesandbox.io/s/dreamy-solomon-9pni5?fontsize=14

这里有个demo，我本来想要实现的功能是类似于3D场景中滚轮的zoom in and zoom out，我希望在zoom的时候，每个sprite的相对距离不会发生变化

layer对象上没有相应的api，所以我选择把所有path扔进一个group里面，但是当group被scale的时候，里面的path却变模糊了，只有hover到sprite上，才会变清晰，有啥更好的办法解决这种需求吗？我觉得放进group里也不是最好的方案

**Comment by akira-cn** [comment]
你可以把group的缓存关掉就不会模糊了，具体就是下面的代码，加一个属性 `enableCache: false`

```js
const group = new Group();
group.attr({
  size: [300, 800],
  pos: [570, 900],
  anchor: [0.5, 0.5],
  enableCache: false,
});
```

**Comment by RyanZhu1024** [comment]
确实可以了，多谢！
