### ISSUE TITLE
集成到Node端不可用

### ISSUE THREAD

**Issue by manyuanrong** [spritejs/spritejs#119]
以前应该是没有问题的，之前用过。现在用不了了
![image](https://user-images.githubusercontent.com/7514524/64007172-3e9aea80-cb46-11e9-9f49-4ed7f29bce00.png)

**Comment by akira-cn** [comment]
你可以 `require('spritejs/src/index.js')` 试试

**Comment by manyuanrong** [comment]
不行 ，用了 import { xx } from "xxx" 这种语法。server side 也不应该用babel这样的东西。建议做spritejs做serverside 的test case
![image](https://user-images.githubusercontent.com/7514524/64088298-5e632600-cd73-11e9-8d88-b1a07acb1a09.png)

**Comment by akira-cn** [comment]
这样的话，用 `require('spritejs/lib/index.js')` 应该可以了。

因为spritejs要build多个环境，那个问题应该是某次webpack升级加了一个globalObject配置导致的问题，你先用`require('spritejs/lib/index.js')`吧，下一版本升级的时候会修改编译脚本修复。

**Comment by manyuanrong** [comment]
`require('spritejs/lib/index.js')` 可以。
还有个小问题，index.d.ts 的位置似乎放得不对。在src里面ts并没有找到

**Comment by akira-cn** [comment]
的确，这个需要编译到lib下，下一版本更新的时候我们一并改一下，你现在可以先把它copy到lib目录下应该就可以了。
