### ISSUE TITLE
如何用一张本地图片作为精灵

### ISSUE THREAD

**Issue by qmhc** [spritejs/spritejs#12]
如果在没开服务器的情况下，我把textures设置为一张本地图片的url时，会报跨域错误，不知道目前有没有解决办法，之后会不会考虑一下使用imgDataUrl作为参数？

**Comment by akira-cn** [comment]
如果不开服务器，你可以把图片转成base64，现在spritejs支持base64的本地图片

比如这样： https://code.h5jun.com/zopet/edit?js,output

由于安全问题，暂不支持直接引用本地图片url
