### ISSUE TITLE
图片在旋转后出现renderRect尺寸长宽增大1的情况。

### ISSUE THREAD

**Issue by MrTsao** [spritejs/spritejs#124]
我现在在做一个比较精细的图片拼版程序，而且需要把拼完后的图片打印出来。这个程序里需要对个别的图片进行（0，90，270）这三个角度的旋转。在旋转后需要知道精确的图片位置、大小，来做一个自动吸附的功能。方便快速处理。但因为图片在旋转后，出现的图片属性renderRect值的不确定。（旋转后图片尺寸在原来的基础上减1，或加1）。特别是在旋转到270度的情况下，这种情况很常见。也有可能根据位置的不同有差异。起初以为原点是中心点的问题而出现的这种情况。测试把中心点就设为初始值的左上角。发现在旋转后，再位移。还是出现这样的问题 。求解决。谢谢。

**Comment by MrTsao** [comment]
/*中点心在左上角，旋转+位移*/
if (rotate == 0) {
                    sprite.attr({
                        rotate: parseInt((sprite.attr('rotate') + degree) % 360),
                        pos: [pos[0] + sprite.originalSize[1], pos[1]]
                    });
                 else if (rotate == 90) {
                    sprite.attr({
                        rotate: parseInt((sprite.attr('rotate') + degree) % 360),
                        pos: [pos[0] - Math.abs(sprite.originalSize[0] - sprite.originalSize[1]), pos[1] + sprite.originalSize[1]]
                    });
                }
                else if (rotate == 180) {
                    sprite.attr({
                        rotate: parseInt((sprite.attr('rotate') + degree) % 360),
                        pos: [pos[0] - sprite.originalSize[0], pos[1] - Math.abs(sprite.originalSize[0] - sprite.originalSize[1])]
                    });
                } else if (rotate == 270) {
                    sprite.attr({
                        rotate: parseInt((sprite.attr('rotate') + degree) % 360),
                        pos: [pos[0], pos[1] - sprite.originalSize[0]]
                    });
                }

**Comment by akira-cn** [comment]
renderRect的大小是指元素的boundingBox，肯定是会跟随着旋转改变大小的。

**Comment by MrTsao** [comment]
你好！
	首先感谢你给我回信。非常谢谢你！

     renderRect 确实是会跟随着旋转而改变大小。但在角度为0度，90度，180度，270度。这些角度的情况下。大小应该是一致的。但我目前碰到的问题。比如0度的情况下，在border-width  为0，的情况下，是210*285(mm),但在旋转后到270度的情况下，可能会根据位置的不同。这个renderRect大小，可能变成 211*285、210*286、211*286、209*285.这几种。



看上图中，红色方框中，在旋转后，因为renderRect尺寸变大了，中间有条缝。没法紧紧贴合。

**Comment by MrTsao** [comment]
<img width="1140" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/21235835/65655320-63ec1d00-e04e-11e9-8ec9-adee3ef663e6.png">

**Comment by akira-cn** [comment]
这种情况的确是个bug，这是因为计算精度的问题导致的，你暂时先用boundingRect代替用renderRect解决这个问题吧，boundingRect的前两个值加上pos属性就是renderRect了，而且没有1px问题。

**Comment by akira-cn** [comment]
这个问题新版已修复
