### ISSUE TITLE
我发现一个bug,路径放在组内, 然后拖动组,有阴影的话会闪动

### ISSUE THREAD

**Issue by xrayffa** [spritejs/spritejs#125]
如果一个路径加了阴影, 放在组里面, 拖动组, 会闪屏,  如果不加阴影, 则不闪
`
  const { Scene, Label, Path, Group } = spritejs;
  const scene = new Scene('#paper', { viewport: ['auto', 'auto'], resolution: [1200, 1200] });

  const layer = scene.layer('fglayer');

  /*组1,拖动时,会闪动*/
  let group1 = new Group();
  group1.attr({
    anchor: [0.5, 0.5],
    bgcolor: "rgba(0,0,0,0.6)",
  });
  layer.append(group1);

  const path1 = new Path({
    path: {
      d: 'M280,250A200,200,0,1,1,680,250A200,200,0,1,1,280,250Z',
      trim: true
    },
    shadow: {
      offset: [15, 15],
      blur: 10,
      color: '#000'
    },
    fillColor: '#839',
  });
  group1.appendChild(path1);

  layer.on('mousemove', (e) => {
    group1.attr({ x: e.x, y: e.y });
  });
  /*如果开启动画,也会闪屏*/
  /*
  group1.animate([
    { pos: [0, 0] },
    { pos: [0, 300] },
  ], {
    duration: 5000,
    iterations: Infinity,
    direction: 'alternate',
  });
  */

  /*路径2,不会闪动*/
  const path2 = new Path({
    path: {
      d: 'M280,250A200,200,0,1,1,680,250A200,200,0,1,1,280,250Z',
      trim: true
    },
    shadow: {
      offset: [15, 15],
      blur: 10,
      color: '#000'
    },
    fillColor: '#839',
  });
  layer.appendChild(path2);
  layer.on('mousemove', (e) => {
    path2.attr({ x: e.x, y: e.y });
  });

`

**Comment by xrayffa** [comment]
今天发现 , 只要把路径有所偏移, 就不会闪屏!

//今天发现,  本来是需要移动group1,但是会闪屏, 如今, 只要轻轻位移路径再移回去,就不会闪屏
  layer.on('mousemove', (e) => {
    group1.attr({ x: e.x, y: e.y });

    path1.attr({
      translate: [1, 1]
    });
    path1.attr({
      translate: [-1, -1]
    });
  });

**Comment by akira-cn** [comment]
已经修复了，你更新到最新版再试一下~
