### ISSUE TITLE
server端 生成的图片尺寸不正确

### ISSUE THREAD

**Issue by deiphi** [spritejs/spritejs#126]
我尝试用nodejs生成截图，但是生成的图片总是800 * 600，而不是设置的尺寸。
`const fs = require('fs');
const { Scene, Sprite, Label } = require('spritejs/lib/index.js');
const scene = new Scene('#test', 1920, 1080);
const layer = scene.layer('bg', { handleEvent: false });
const text = new Label('Hello Sprite!');
const bg = new Sprite({
    size: [1920, 1080],
    pos: [0, 0],
    bgcolor: 'gray'
});

text.attr({
    anchor: [0.5, 0.5],
    pos: [500, 500],
    font: '46px Arial',
    color: 'blue',
    bgcolor: 'white',
    textAlign: 'center',
});

layer.append(bg);
layer.append(text);

(async function () {
    const canvas = await scene.snapshot()
    fs.writeFileSync('snap.png', canvas.toBuffer()) // 生成的尺寸是 800*600 为啥不是 1920 * 1080？
}());
`

**Comment by akira-cn** [comment]
```js
const scene = new Scene('#test', {
  viewport: [1920, 1080],
});
```
你好，这样设置就可以了。

**Comment by deiphi** [comment]
> ```js
> const scene = new Scene('#test', {
>   viewport: [1920, 1080],
> });
> ```
> 
> 你好，这样设置就可以了。

试了一下，有效，非常感谢：）
