### ISSUE TITLE
快速移动丢帧怎么优化啊

### ISSUE THREAD

**Issue by lunaticnotcrazy** [spritejs/spritejs#13]
```js

p1.on('touchstart', evt => {
      startX = evt.layerX
      startY = evt.layerY
      sprites = p1.attr('pos')
    })
    p1.on('touchmove', evt => {
      const dx = evt.layerX - startX,
        dy = evt.layerY - startY
      p1.attr({
        'pos': [sprites[0] + dx, sprites[1] + dy]
      })
    })

```
在touchstart 保存 起始位置 移动时监听 位置变化 
精灵移动慢些还好 如果 移动快了 会出现丢帧 的 情况 
有没有 办法 优化啊?

**Comment by akira-cn** [comment]
这个不仅仅是丢帧，如果你注册touchmove事件在元素上来做拖拽，因为设备的touchmove事件本来就是有一定频率来触发的，有可能你手指瞬间移出了p1的区域，但是没有触发到p1的touchmove

一般我们拖拽把touchstart注册在p1上，touchmove和touchend应该注册在layer上，如果你是浏览器，而且layer的大小没有全屏，最好将touchmove和touchend注册在document上。

然后才是丢帧——其实也不是丢帧——因为你的touch位置在两次touchmove间隔其实是有跳跃的，如果要流畅动画需要做补间，把两次间隔的动画给补上

可以类似这样做：

```js
let startPosition = null
p1.on('touchstart', evt => { 
    startX = evt.layerX 
    startY = evt.layerY 
    startPosition = p1.attr('pos') 
}) 

layer.on('touchmove', evt => {
     if(startPosition != null) {
        const deltaX = evt.layerX - startX,
            deltaY = evt.layerY - startY
          
        const time = (deltaX ** 2 + deltaY ** 2) * 1e-4
        p1.transition(time).attr({pos: [startPosition[0] + deltaX, startPosition[1] + deltaY]})
    }
})

layer.on('touchend', evt => {
    startPosition = null
})
```

**Comment by akira-cn** [comment]
好像还是不能（也不应该）用transition

```js
let startPosition = null
p1.on('touchstart', evt => { 
    startX = evt.layerX 
    startY = evt.layerY 
    startPosition = p1.attr('pos') 
}) 

layer.on('touchmove', evt => {
     if(startPosition != null) {
        const deltaX = evt.layerX - startX,
            deltaY = evt.layerY - startY
          
        p1.attr({pos: [startPosition[0] + deltaX, startPosition[1] + deltaY]})
    }
})

layer.on('touchend', evt => {
    startPosition = null
})
```

可以试试这样，我想应该就能解决你的问题~

**Comment by welefen** [comment]
@akira-cn 这个非 layer 绑定 touchmove 事件时是不是可以给个【不建议绑定在当前元素，建议绑定在 layer 上的】 提示？

**Comment by akira-cn** [comment]
@welefen 有可能除了拖拽之外做其他事情的确需要touchmove在当前元素，回头可以考虑单独提供一组drag事件

**Comment by lunaticnotcrazy** [comment]
嗯 好的 多谢 我试试哈

**Comment by lunaticnotcrazy** [comment]
多谢给我解答哈 不过
不好意思 我的 问题 没描述清楚
我的 环境是微信小程序 
我给 canvas 元素添加的  bindtouchmove 事件
然后 new path() 新的元素 绘图完成后 给 元素分别绑定的 ‘touchmove’ 和 ‘touchstart’事件 
![animation1](https://user-images.githubusercontent.com/21071051/42072995-95474172-7b96-11e8-909f-5a6cffb0c305.gif)
类似 这样 慢一点 会 好点 
如果 快了 元素 就不会 随鼠标移动
不知道 是写法 哪里不对了 
const scene = new Scene(2.0)
    this.scene = scene
    const layer = scene.layer('fglayer')
    const p1 = new Path()
    const moveX = 0
    const pieceSize = 120
    const moveY = pieceSize
    const outSide = '1,1,0'
    const inSide = '0,1,1'
    const cirler = 20
    const sideState = {}
    const bottomState = 'L44 124 A20 20,0, 1, 1,76,124'
    const bottomState1 = 'L44 124 A20 20,0, 1, 1,76,124'
    const bottomSide = `M${moveX} ${moveY} ${bottomState} L${moveX + pieceSize} ${moveY}`
    const rightSide = `L${moveX + pieceSize - 4} 76 A20 20,1,1,0,${moveX + pieceSize - 4}, 44 L${moveX + pieceSize} 0`

    const topSide = `L0 0`
    const leftSide = `L${moveX} ${moveY}Z`
    p1.attr({
      path: {
        //  d: `M10,80 q${controller},-80 350,0`, 
        // d: 'M20 80 L42 82 A10 10,0, 1, 1,58,82 L80 80', // 凹陷 
        d: bottomSide + rightSide + topSide + leftSide, // 凸起
      },
      strokeColor: '#033',
      lineWidth: 2,
      pos: [20, 20]
    })
    let startX = null;
    let startY = null;
    let sprites = null;
    p1.on('touchstart', evt => {
      startX = evt.layerX
      startY = evt.layerY
      sprites = p1.attr('pos')
    })
    p1.on('touchmove', evt => {
      const dx = evt.layerX - startX,
        dy = evt.layerY - startY
      p1.attr({
        'pos': [sprites[0] + dx, sprites[1] + dy]
      })
    })
    layer.append(p1)`

**Comment by akira-cn** [comment]
touchmove 要绑在 canvas 元素上。你这个问题就是快速移动的时候有可能手指移出了p1元素但是mousemove事件还没来得及检测到

不管是在网页、手机还是小程序，一般我们实现拖拽都是要把touchmove和touchend给注册在外边的大的容器上

**Comment by lunaticnotcrazy** [comment]
如果 元素一直 是跟随 手指的移动 就不会 出现你说的 可能是手指移出了 p1元素的 问题了吧
我尝试过小程序的canvas api 写法 手指移动 canvas 重新绘制 图形 并没有出现 类似的 情况
即使再移动的 再快 手指也不会脱离 
现在出现脱离的情况 是因为 控件 是只给 这个元素 添加的 事件么 还是 给canvas 添加的 事件
无论怎么样 如果我要是用控件的话 无法实现拖动 效果 不能让人一直 确保手指不脱离需要 移动的 元素吧
还有 你说 给外边的 大容器注册事件 和 直接给 canvas注册事件 有什么区别么
我的 canvas 大小 和外侧 容器大小是 一样大的 
再说 咱控件的 写法 不是 给 canvas添加的 么 我给 外侧容器注册事件 但是 并不奏效啊 

真心 请教哈  多谢你 你能 回复我 
确实 实在 项目中 有类似 的 使用场景 也调研了 过很多 方法 
再次多谢哈

**Comment by akira-cn** [comment]
https://oss.so/article/81 
你看一下这个就明白了，touch和mouse的问题是一致的，canvas api写可以就是因为事件的有效区域一直在canvas上，你要把touchmove事件注册在canvas上而不是当前这个元素上。

如果 元素一直 是跟随 手指的移动  —— 这个只是理想情况

实际上程序里（不管是小程序还是网页），touchmove事件都不可能一直连续触发的，它有一个时间间隔，比如我们假设两次touchmove触发的频率10Hz，也就是两次touchmove事件触发的时间间隔是100毫秒，那么你第一次移动手指头在p1元素里面，那么p1会跟着手指头移动，然后快速（在100毫秒内）将手指头滑出p1的区域，那么第二次touchmove触发的时候，因为你的手指头已经在p1外面了，那么这时候并不会触发p1的touchmove了。

所以我们做拖拽要这么做：

- 第一步：给p1注册touchstart事件，当手指头放在p1上时，将p1状态置为拖拽状态
- 第二步：给p1外面的大容器（通常是全屏的canvas）注册touchmove事件，移动手指头，监听touchmove事件（在sprite小程序里，你可以把touchmove事件监听放在layer上，监听layer的touchmove事件）根据手指头移动的距离，改变p1的位置
- 第三步：当手指头离开屏幕时，将p1状态重新置为非拖拽

这样就可以了

你用原生canvas api的时候，其实事件始终是在canvas上的，p1只是随着你在canvas上移动重新画而已

那么同样的，你用spritejs的时候，也应该是把事件注册在layer上，随着手指移动重新改变p1的位置，而不是注册在p1上。

**Comment by lunaticnotcrazy** [comment]
嗯，我给p1注册方法而不是给canvas注册事件的一个原因是我有好多p1,一开始打算的是如果我要是能给不同的p1(不知道叫什么好 元素 好像不合适)注册事件最好,这样就不用做额外的处理(类似如果给canvas注册 我需要判断当前 位置 是那个小的p1等 额外的 处理),所以 我看到spritesjs 的时候 眼前一亮 以为可以得,现在想想 还是 太年轻了 ,我现在实现的思路是 用canvas 做裁剪 然后生成一张图片 把图片渲染给小程序的标签movable-vew注册事件 基本是能 满足 需求了 但是 性能 代码 都需要 个人 额外的 优化
接下来有时间 我还是 会 继续关注 spritesjsi的 
再次感谢 给我的 回答 辛苦了哈

**Comment by akira-cn** [comment]
注册在layer上也不需要自己判断哪个元素被踩到，事件参数里面event.targetSprites里面有存放踩中的元素。

另外我们官网的demo里面有拖拽的例子啊，你看一下 http://sprite.org/ 点 get started 那个按钮进到文档，看高级用法里面事件相关的，有拖拽的例子，不会掉的

**Comment by akira-cn** [comment]
http://spritejs.org/
