### ISSUE TITLE
如何在画布上播放gif图

### ISSUE THREAD

**Issue by jc840031139** [spritejs/spritejs#139]

**Comment by akira-cn** [comment]
将gif图导出成一帧一帧的图片，用preload预加载到页面上，然后用动画播放就可以了

**Comment by jc840031139** [comment]
是动态的更改精灵的texture吗

**Comment by jc840031139** [comment]
我还想问一下 您这边有技术交流群吗

**Comment by akira-cn** [comment]
是的，https://spritejs.org/demo/#/quick_start 这里面有很多例子都是动态改texture的

有微信交流群，不过人数超过了200，你只能留个联系方式或者找人把你加进去。

**Comment by jc840031139** [comment]
您这边能加我微信一下吗 jc75212 拉我入群
