### ISSUE TITLE
 canvas  drawimage   IndexSizeError: The index is not in the allowed range.

### ISSUE THREAD

**Issue by zhiqiang21** [spritejs/spritejs#14]
![image](https://user-images.githubusercontent.com/3990411/41907262-e91e38f8-7972-11e8-98e0-eb051b558c5f.png)

can you help me ?

**Comment by akira-cn** [comment]
你能贴一段代码上来吗？你这个代码不是spritejs的哦。

不过我看错误可能是你用的iconSize的问题，要么是类型不对，iconSize是数组，要么是实际上不应该用iconSize而是用iconWidth和iconHeight (iconSize = iconWidth * iconHeight?)

iconSize的范围超过了浏览器里canvas允许的宽高最大值

**Comment by zhiqiang21** [comment]
问题找到啦谢谢月影老师哈。我的这个drawimge是动态的绘制一个会变化的图像。在一次变化的时候我给img.src=''导致的程序错误。
