### ISSUE TITLE
请问，如何重绘？

### ISSUE THREAD

**Issue by aimeiyijia** [spritejs/spritejs#140]
绘制出的内容有一部分需要重绘，请问怎么做？谢谢！

**Comment by akira-cn** [comment]
SpriteJS的元素在属性更新的时候会自动重绘，不需要刻意去控制它。不过如果要和其他第三方库协同工作的话，可以使用外部时钟。

https://spritejs.org/#/zh-cn/guide/ticker 这是关于外部时钟的文档

**Comment by aimeiyijia** [comment]
收到，谢谢！
