### ISSUE TITLE
TypeError: _this.getResolution is not a function. (In '_this.getResolution()', '_this.getResolution' is undefined)

### ISSUE THREAD

**Issue by superEdwardLong** [spritejs/spritejs#141]
多线程worker
TypeError: _this.getResolution is not a function. (In '_this.getResolution()', '_this.getResolution' is undefined)
spritejs.js 行37065

`if (!options.canvas) {
        var _this$getResolution = _this.getResolution(),
            width = _this$getResolution.width,
            height = _this$getResolution.height;

        var canvas = _mesh_js_core__WEBPACK_IMPORTED_MODULE_7__["ENV"].createCanvas(width, height, {
          offscreen: false
        });
        if (canvas.style) canvas.style.position = 'absolute';
        if (canvas.dataset) canvas.dataset.layerId = options.id;
        options.canvas = canvas;
      }`

**Comment by superEdwardLong** [comment]
官网上的示例也报同样的错误
https://spritejs.org/demo/#/doc/worker

**Comment by akira-cn** [comment]
能麻烦报告一下你使用的浏览器环境吗？我们在chrome浏览器测试并没有发现问题。

**Comment by superEdwardLong** [comment]
> 能麻烦报告一下你使用的浏览器环境吗？我们在chrome浏览器测试并没有发现问题。

Safari 浏览器 13.0.4

**Comment by akira-cn** [comment]
查过了，这是Safari浏览器的一个bug。。。它不能正常继承Worker类。

比如 ：

```js
class MyWorker extends Worker {

}

const worker = MyWorker('worker.js');

console.log(worker instanceof MyWorker); // 在safari下是false，实际上这时候的worker是Worker对象，并不是MyWorker对象
```

我们会看一下怎么做兼容性处理。

**Comment by akira-cn** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/transferControlToOffscreen

查了一下safari虽然支持Worker，但是它不支持OffscreenCanvas

所以虽然不能正常继承Worker类的这个问题能修复，但是没有OffscreenCanvas，也是不能使用多线程渲染的

这个问题只能等待未来Safari支持了OffscreenCanvas才能解决。

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/transferControlToOffscreen
