### ISSUE TITLE
有没有基于 web animation api 的 fps 计算解决方案啊？

### ISSUE THREAD

**Issue by XXXMrG** [spritejs/spritejs#146]
传统的 fps 计算方案是通过在循环代码中计算帧数和时间来实现的，而针对于 sprite 的关键帧动画要如何才能计算 fps 呢？
可以参考 `PerformanceFrameTiming ` 或是 animation timeline 么？

**Comment by akira-cn** [comment]
现在不建议用api自己算fps了，你要测性能的话，打开chrome的开发者工具，切换到Rendering，把FPS meter选项给勾上，浏览器就可以显示fps。

**Comment by XXXMrG** [comment]
OK 多谢团长 🤝
