### ISSUE TITLE
v3版本没有碰撞检测了吗

### ISSUE THREAD

**Issue by chang888** [spritejs/spritejs#150]
延续之前v2的没有update事件, OBBCollision方法好像也没了,请问如何检测碰撞
![image](https://user-images.githubusercontent.com/38515221/75645662-c7274e80-5c81-11ea-8d81-dcce4c8f13f9.png)

**Comment by akira-cn** [comment]
我把 OBBCollision 从核心库里面去掉了，你可以自己实现的，原理和 v2 的 OBBCollision 一样。

没有update事件，我考虑一下是否要添加layer的beforeRender/afterRender事件。但是你现在可以用以下方式： 

```js
layer.tick(() => {
    碰撞检测写在这里面
});
```

**Comment by peade** [comment]
> 我把 OBBCollision 从核心库里面去掉了，你可以自己实现的，原理和 v2 的 OBBCollision 一样。
> 
> 没有update事件，我考虑一下是否要添加layer的beforeRender/afterRender事件。但是你现在可以用以下方式：
> 
> ```js
> layer.tick(() => {
>     碰撞检测写在这里面
> });
> ```

有没有相关具体实现的例子么？
