### ISSUE TITLE
试了一下在node端的示例，报错不能用

### ISSUE THREAD

**Issue by deiphi** [spritejs/spritejs#152]
官方示例：
`
const fs = require('fs');
const {Container} = require('../lib/polyfill/node-canvas');
const {Scene, Sprite} = require('../lib');

const container = new Container(512, 512);
const scene = new Scene({container});
const fglayer = scene.layer('fglayer');
const url = 'https://p0.ssl.qhimg.com/t01a72262146b87165f.png';

const sprite = new Sprite();
sprite.attr({
  pos: [256, 256],
  size: [100, 100],
  anchor: 0.5,
  bgcolor: 'red',
  texture: url,
});

fglayer.append(sprite);

setTimeout(() => {
  const canvas = scene.snapshot();
  fs.writeFileSync('snap.png', canvas.toBuffer());
}, 1000);
`

修正路径'spritejs/lib/platform/node-canvas' 也报错。

**Comment by deiphi** [comment]
你好，报错是这样的。
![20200305112547err](https://user-images.githubusercontent.com/3659715/75945184-7fe4cc00-5ed4-11ea-91f4-1971421f63ee.png)

**Comment by akira-cn** [comment]
这是因为，node-canvas-webgl 没有安装，因为我把这个库放在 devDependencies 下（主要是大部分web用户不需要安装它），所以这个需要自己装一下

```bash
npm install node-canvas-webgl
```

这样应该就好了。

**Comment by deiphi** [comment]
你好，安装了node-canvas-webgl，然后报其他错误了，如图：

![20200305133143err](https://user-images.githubusercontent.com/3659715/75951018-d3abe100-5ee5-11ea-84d1-42bc2af4e3b5.png)

**Comment by akira-cn** [comment]
windows下似乎不支持node-canvas，这个你得用linux环境下的node跑了

**Comment by deiphi** [comment]
酱紫，但是 spritejs v2 是支持 node-canvas 的，我当时使用过， 是spritejs  v3.0 不支持吗？

**Comment by akira-cn** [comment]
哦，如果node-canvas可以用，你用旧的 node-canvas 应该可以。

你把 lib/platform/node-canvas.js 那个文件内容复制出来，保存成你自己的js文件，修改下面这句

```js
var _nodeCanvasWebgl = require("node-canvas-webgl");
```

替换成

```js
var _nodeCanvasWebgl = require("node-canvas");
```

然后依然安装 node-canvas 而不是 node-canvas-webgl

这样试试，应该可以。
