### ISSUE TITLE
在angular8环境下报错不能用

### ISSUE THREAD

**Issue by gemingg** [spritejs/spritejs#153]
在angular8环境下报错不能用

**Comment by gemingg** [comment]
ERROR in node_modules/spritejs/typings/spritejs.d.ts(151,40): error TS2304: Cannot find name 'OffscreenCanvas'.
node_modules/spritejs/typings/spritejs.d.ts(161,26): error TS2304: Cannot find name 'WebGL2RenderingContext'.
node_modules/spritejs/typings/spritejs.d.ts(262,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/spritejs/typings/spritejs.d.ts(266,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/spritejs/typings/spritejs.d.ts(270,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/spritejs/typings/spritejs.d.ts(274,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/spritejs/typings/spritejs.d.ts(864,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/spritejs/typings/spritejs.d.ts(868,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/spritejs/typings/spritejs.d.ts(872,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/spritejs/typings/spritejs.d.ts(876,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/spritejs/typings/spritejs.d.ts(880,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/spritejs/typings/spritejs.d.ts(884,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/spritejs/typings/spritejs.d.ts(888,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/spritejs/typings/spritejs.d.ts(892,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by akira-cn** [comment]
这是typescript版本太老了吧，升级一下typescript应该就好了
