### ISSUE TITLE
加载大图 黑屏

### ISSUE THREAD

**Issue by xiang473535976** [spritejs/spritejs#156]
https://zgyrmfy-wfy-in-test-1258757587.cos.ap-beijing.myqcloud.com/0.4729464615246759canvasBg.png
可以试一试  加载这种大图 出来的是黑色背景 
电脑浏览器没问题 用手机浏览器就会出问题
https://zgyrmfy-wfy-in-test-1258757587.cos.ap-beijing.myqcloud.com/0.29088296266819724
加载成这样了   黑色  
1.我是直接加载的本地图片   如果用scene.preload加载远程图片就会一直无响应  不回调Promise
现在我的措施是吧大图拆分成九张小图    一张一张的拼接(蛋疼啊)
请大佬有空看看 我用的最新版本
右下角那张小图就能加载出来
![Screenshot_2020-03-25-09-25-31-609_mark via](https://user-images.githubusercontent.com/18111614/77492253-09a40b80-6e7b-11ea-9087-1669f7826a97.jpg)

**Comment by akira-cn** [comment]
你这个图片太大了确实会黑屏的，因为超过了canvas所能承受的宽高。。。

**Comment by xiang473535976** [comment]
> 你这个图片太大了确实会黑屏的，因为超过了canvas所能承受的宽高。。。

能处理不 ？

**Comment by akira-cn** [comment]
这个框架层面处理不了，你可以用第三方库或者自己处理一下，估计思路就是加载到image中然后用canvas分片绘制再把分片绘制好的图片返回。

**Comment by xiang473535976** [comment]
> 这个框架层面处理不了，你可以用第三方库或者自己处理一下，估计思路就是加载到image中然后用canvas分片绘制再把分片绘制好的图片返回。
我现在吧图片切成了九份  搞的…………  还是等你们更新 哈哈    毕竟不能加载大图 还是有点蛋疼

**Comment by akira-cn** [comment]
大图在canvas里面确实没法处理，内存限制。而且因为浏览器和其他运行环境不同，对图片大小的限制还没有一个固定值。所以我们不会更新处理这个。你最好用第三方工具，这样就方便你处理大图。很多canvas/webgl应用中碰到处理大图都是自己把图切片处理的。比如地图应用，都是把地图切成瓦片分块加载的。

**Comment by xiang473535976** [comment]
> 大图在canvas里面确实没法处理，内存限制。而且因为浏览器不同版本、以及其他运行环境的差异，各个端对图片大小的限制还没有一个固定值。所以我们不会更新处理这个。你最好用第三方工具，这样就方便你处理大图。很多canvas/webgl应用中碰到处理大图都是自己把图切片处理的。比如地图应用，都是把地图切成瓦片分块加载的。

ok  谢谢了

**Comment by akira-cn** [comment]
spritejs的元素的texture属性可以支持url、img、canvas，所以你可以自己写一个库把图片切片之后传给spritejs的元素，这样你就不用手工去拆分图片了

**Comment by xiang473535976** [comment]
> spritejs的元素的texture属性可以支持url、img、canvas，所以你可以自己写一个库把图片切片之后传给spritejs的元素，这样你就不用手工去拆分图片了

好的  感谢 我晚点去试一试
