### ISSUE TITLE
animate监听动画次数

### ISSUE THREAD

**Issue by Mypika** [spritejs/spritejs#158]

**Comment by Mypika** [comment]
我想知道当iterations值为Infinity时，是否有办法监听当前动画执行的次数呢？
现在的解决办法是通过动画执行的时间来计算次数，请问有没有更好的办法呢？

**Comment by akira-cn** [comment]
因为内置的动画按照web animation api标准实现，所以没有定义这个事件。
你可以把iterations设为1，然后这么用：

```js
while(true) {
    await anim.finished;
    执行动作
    anim.play();
}
```

**Comment by Mypika** [comment]
好的，谢谢
