### ISSUE TITLE
v3版本使用，在移动端Safari浏览器上显示不出来

### ISSUE THREAD

**Issue by yxb94616** [spritejs/spritejs#171]
移动端H5不便调试，try catch抛出的是在这行代码报的错/(ㄒoㄒ)/~~
const { Scene, Sprite, Group } = spritejs;

浏览器版本：5.0 (iPhone; CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1

**Comment by akira-cn** [comment]
移动端safari版本是不是不支持参数解构，你用ES5的语法写，不要用ES6的语法写。

**Comment by yxb94616** [comment]
> 移动端safari版本是不是不支持参数解构，你用ES5的语法写，不要用ES6的语法写。

` var Scene = spritejs.Scene, var Sprite = spritejs.Sprite;` 这样也不行呢；
而且把github提供的V3版本**Quick Start**例子修改成ES5，然后在真机上测试也显示不出来

**Comment by akira-cn** [comment]
这个是之前safari的兼容性问题，我修复了，你可以再试一下
