### ISSUE TITLE
如何渲染一个视频呢

### ISSUE THREAD

**Issue by satawait** [spritejs/spritejs#173]
想将一个视频渲染进去，但是总是只显示第一帧，不更新，请问应该怎么让其更新呢，我的代码如下
`const canvas = document.createElement('canvas')`
		`canvas.width = 1200`
		`canvas.height = 1200`
		`const ctx = canvas.getContext('2d')`
		`video.addEventListener('playing', draw)`
		`function draw() {`
			`ctx.drawImage(video, 0, 0, 1200, 1200)`
			`video.attr({`
				`texture: canvas`
			`})`
			`requestAnimationFrame(draw)`
		`}`

**Comment by akira-cn** [comment]
因为canvas的引用是同一个，所以video不会自动刷新layer，你调一下forceUpdate()强制刷新就行

```js
const canvas = document.createElement('canvas')
canvas.width = 1200
canvas.height = 1200
const ctx = canvas.getContext('2d')
video.addEventListener('playing', draw)

function draw() {
    ctx.drawImage(video, 0, 0, 1200, 1200)
    video.attr({
        texture: canvas
    })
    video.forceUpdate();
    requestAnimationFrame(draw)
}
```

**Comment by akira-cn** [comment]
另外，你也可以直接用layer.tick

```js
const canvas = document.createElement('canvas')
canvas.width = 1200
canvas.height = 1200
const ctx = canvas.getContext('2d')
video.addEventListener('playing', draw)

layer.tick(() => {
    ctx.drawImage(video, 0, 0, 1200, 1200)
    video.attr({
        texture: canvas
    })
})
```

这两种方法都可以。

**Comment by akira-cn** [comment]
这个确实还是有点问题，我们下一个版本修复一下

**Comment by satawait** [comment]
> 这个确实还是有点问题，我们下一个版本修复一下

辛苦啦

**Comment by akira-cn** [comment]
已经修复了，现在可以啦，调用forceUpdate()或者直接用layer.tick

我加了一个例子 https://spritejs.org/demo/#/video 供参考
