### ISSUE TITLE
小程序真机报错

### ISSUE THREAD

**Issue by wilhantian** [spritejs/spritejs#174]
使用dist/sprite.min.js文件，在真机中报Function(...) is not a function错误

**Comment by akira-cn** [comment]
小程序需要在项目中配置一下这个文件不要压缩

**Comment by xingzhisuozai930** [comment]
具体怎么配置啊

**Comment by wilhantian** [comment]
> 具体怎么配置啊

project.config.json > babelSetting > ignore > 具体js文件路径
