### ISSUE TITLE
spritejs如何实现双缓冲？

### ISSUE THREAD

**Issue by CraxGrix** [spritejs/spritejs#179]
翻了下好像有offscreen相关的参数，但是好像没有文档？是不是我创建一个offscreen然后调用render方法就行了？

**Comment by akira-cn** [comment]
你具体什么场景需要用到双缓冲？

spritejs的OffscreenCanvas不是用来实现双缓冲的，那个主要是用来实现多线程里worker渲染，当然你也可以直接创建一个layer的时候传一个offscreen的canvas对象进去，然后自己去做双缓冲。但是一般的webgl渲染没有必要做双缓冲，那样还耗性能。

**Comment by CraxGrix** [comment]
> 你具体什么场景需要用到双缓冲？
> 
> spritejs的OffscreenCanvas不是用来实现双缓冲的，那个主要是用来实现多线程里worker渲染，当然你也可以直接创建一个layer的时候传一个offscreen的canvas对象进去，然后自己去做双缓冲。但是一般的webgl渲染没有必要做双缓冲，那样还耗内存。

我这边写一个GIS相关的项目用SpriteJS画一些路径和图标，但是缩放的时候路径和图标会出现闪烁，可能是SpriteJS的刷新机制没有契合到我现有的框架？

**Comment by akira-cn** [comment]
这个应该不是缓冲的问题，你可以把具体出现闪烁的示例代码写出来，用codepen或者其他在线的代码平台，这样我们可以有针对的排查一下。

**Comment by CraxGrix** [comment]
非常感谢，我这几天再找一下相关的
