### ISSUE TITLE
Bitmap font feature?

### ISSUE THREAD

**Issue by littlee** [spritejs/spritejs#18]
Recently, I am looking for a simple canvas library with bitmap font feature which is compatible with wechat mini app.

**Comment by akira-cn** [comment]
我想了一下，大概需要写一个转换工具，把bmGlyph生成的配置文件解析成JS模块，在微信小程序里面import进去，然后写一个BitmapFont类读取配置信息和png，把文字渲染出来

这个后续写一个sprite-extend-bmfont的库来支持吧

**Comment by akira-cn** [comment]
写了bitmap的扩展： https://github.com/spritejs/sprite-extend-bmfont

你可以试一下

**Comment by RockyF** [comment]
amazing!!!

**Comment by littlee** [comment]
That's so diao!
