### ISSUE TITLE
如何优化事件派发所带来的页面卡顿

### ISSUE THREAD

**Issue by CraxGrix** [spritejs/spritejs#180]
画布上有几千个物体并且都注册了mouseenter click等等事件，每次拖动画布或者鼠标滑过时都会造成比较严重的卡顿，看了一下性能分析发现耗时都集中在事件派发的函数，想问一下有什么比较好的解决思路？

**Comment by akira-cn** [comment]
最好不要每个都注册事件，把click事件注册在父容器上，用事件冒泡。不过mouseenter事件不能冒泡。如果你的物体是规则的图形，可以将事件注册在外层，然后自己计算碰撞。不然的话事件太多肯定会卡的。

**Comment by CraxGrix** [comment]
> 最好不要每个都注册事件，把click事件注册在父容器上，用事件冒泡。不过mouseenter事件不能冒泡。如果你的物体是规则的图形，可以将事件注册在外层，然后自己计算碰撞。不然的话事件太多肯定会卡的。

好的了解了，刚才已经用RxJS做了一个事件流来判断，这个问题就解决了。
