### ISSUE TITLE
使用offscreencanvas渲染，render函数耗时过久

### ISSUE THREAD

**Issue by CraxGrix** [spritejs/spritejs#182]
![image](https://user-images.githubusercontent.com/16173957/84335394-50c2b280-abc7-11ea-9c39-daaefb453c83.png)
每次的执行时间为40ms左右，而且layer-worker无法识别handleEvent参数。

**Comment by akira-cn** [comment]
handleEvent参数测试了是没有问题的：

```js
const container = document.getElementById('stage');
const scene = new spritejs.Scene({
  container,
  width: 1200,
  height: 600,
});

scene.layer('fglayer', {worker: './worker.js', handleEvent: false}); // 这样不会把事件传给LayerWorker
```

你用worker渲染不会造成render耗时的问题，因为offscreen canvas是通过transfer的方式直接映射到worker线程中去，被worker线程的layer操作的。

你仔细看一下这个示例，按照这个例子来做

https://spritejs.org/demo/#/doc/worker

**Comment by CraxGrix** [comment]
> handleEvent参数测试了是没有问题的：
> 
> ```js
> const container = document.getElementById('stage');
> const scene = new spritejs.Scene({
>   container,
>   width: 1200,
>   height: 600,
> });
> 
> scene.layer('fglayer', {worker: './worker.js', handleEvent: false}); // 这样不会把事件传给LayerWorker
> ```
> 
> 你用worker渲染不会造成render耗时的问题，因为offscreen canvas是通过transfer的方式直接映射到worker线程中去，被worker线程的layer操作的。
> 
> 你仔细看一下这个示例，按照这个例子来做
> 
> https://spritejs.org/demo/#/doc/worker

好的，我大概知道了，我之前以为可以在主线程直接操作Worker的Layer，结果还是要PostMessage数据到Worker中再进行处理。

**Comment by akira-cn** [comment]
你最好在worker中直接用fetch获取worker中的layer需要的数据，这样节省资源，postMessage也是有开销的。当然如果一定要用postMessage，数据量大的话也最好用transfer的方式传。
