### ISSUE TITLE
海量POI渲染如何才能保证性能？

### ISSUE THREAD

**Issue by CraxGrix** [spritejs/spritejs#187]
月影大大你好，我这边是拿来做GIS相关的项目，屏幕上会渲染至少3000+图形，点或者三角形，用户拖拽地图会对这些图形进行相对应的位置更新，如果同时创建那么多Shape就会导致比较多的内存占用，而且每次draw的时候也会卡顿，我想问一下除了offscreencanvas以外还有什么比较好的解决方案呢？

谢谢～

**Comment by akira-cn** [comment]
才3000+图形，一般来说只要用对方法，不会有问题，你可以看文档里提升性能的方式： https://spritejs.org/#/zh-cn/guide/performance

另外cloud方式渲染可以达到绘制更多的元素，这是渲染50000个图形的例子： https://spritejs.org/demo/#/benchmark/cloud_spots

至于事件处理，我可以提供你参考的思路就是将layer分为两层，一层处理事件，一层只负责绘制，负责绘制layer将handleEvent设为false，拖拽的时候将选中元素复制到处理事件的那个layer去操作即可。

**Comment by CraxGrix** [comment]
> 才3000+图形，一般来说只要用对方法，不会有问题，你可以看文档里提升性能的方式： https://spritejs.org/#/zh-cn/guide/performance
> 
> 另外cloud方式渲染可以达到绘制更多的元素，这是渲染50000个图形的例子： https://spritejs.org/demo/#/benchmark/cloud_spots
> 
> 至于事件处理，我可以提供你参考的思路就是将layer分为两层，一层处理事件，一层只负责绘制，负责绘制layer将handleEvent设为false，拖拽的时候将选中元素复制到处理事件的那个layer去操作即可。

感谢
