### ISSUE TITLE
是否打算出一套基础UI库

### ISSUE THREAD

**Issue by RockyF** [spritejs/spritejs#19]
就是一下基础的UI组件，Button、List之类的组件

**Comment by RockyF** [comment]
真是此想法，用flexbox比其他布局都适合！

还有一个问题，可否出个typescript的申明文件方便ts开发，就像spritejs.d.ts

**Comment by RockyF** [comment]
flex布局是打算自己实现还是用yoga之类的现成的库呢？
yoga的库压缩版有390kB，作为web大了点。
如果自己实现的话可以做一个轻量级的实现！

**Comment by akira-cn** [comment]
flex布局winter大大帮忙实现了一版，现在已经支持了 http://spritejs.org/#/zh-cn/guide/flexlayout

一些最新的属性还不支持，但是基本上能用了

**Comment by RockyF** [comment]
牛逼得不行啊！！！
