### ISSUE TITLE
[types]  parameter type should  convert by Partial

### ISSUE THREAD

**Issue by odex21** [spritejs/spritejs#190]
```ts
//replace 
export class Node  {
  animate (frames: Array<Attr>>, timing: Timing): Animation
}
//to
export class Node  {
  animate (frames: Array<Partial<Attrs>>, timing: Timing): Animation
}
```
原先的写法，在ts里会报错，因为Attr里所有属性都不是可选项。

**Comment by odex21** [comment]
我可以就这个修改提交个PR

ps: 顺便吐槽下，隔壁3d ext 的类型也有很多问题，幸亏vite 用的esbuild 打包ts，不然完全开发不了

**Comment by liulinboyi** [comment]
> 我可以就这个修改提交个PR
> 
> ps: 顺便吐槽下，隔壁3d ext 的类型也有很多问题，幸亏vite 用的esbuild 打包ts，不然完全开发不了

抱歉，上次补充Attrs属性声明时，忘了修改其他使用Attrs声明的地方改为可选属性了。

**Comment by akira-cn** [comment]
> 我可以就这个修改提交个PR
> 
> ps: 顺便吐槽下，隔壁3d ext 的类型也有很多问题，幸亏vite 用的esbuild 打包ts，不然完全开发不了

sprite-extend-3d 的 typings 如果有问题也麻烦帮忙提个PR呗，主要我不是很懂TypeScript。

谢谢~~

**Comment by liulinboyi** [comment]
> > 我可以就这个修改提交个PR
> > ps: 顺便吐槽下，隔壁3d ext 的类型也有很多问题，幸亏vite 用的esbuild 打包ts，不然完全开发不了
> 
> sprite-extend-3d 的 typings 如果有问题也麻烦帮忙提个PR呗，主要我不是很懂TypeScript。
> 
> 谢谢~~

![image](https://user-images.githubusercontent.com/41336612/86535340-35bb3800-bf12-11ea-8028-6b765ffc8e0e.png)
sprite-extend-3d 引用了spritejs中的类型定义，我把这部分引发的错误更正了。
![image](https://user-images.githubusercontent.com/41336612/86535389-8a5eb300-bf12-11ea-87df-23e76f108a49.png)
这里有报错，更正了。

目前能找到的问题更正了。
感谢您提出问题，在您@odex21开发中使用sprite-extend-3d有其他报错 ，希望您修复下，不胜感激！
