### ISSUE TITLE
layer3d 的bgcolor和border好像设置了也不能生效

### ISSUE THREAD

**Issue by xinde** [spritejs/spritejs#195]
看有这个属性，测试了下
layer3d.attributes.bgcolor="red"
layer3d.attributes.border=[2, 'rgba(255,0,0,1)']

是我写得有问题么？

**Comment by akira-cn** [comment]
layer3d 本来就不能用 bgcolor 和 border，你要设置这个，直接用 layer3d.canvas.style 来设置。

**Comment by xinde** [comment]
@akira-cn  好的，谢谢！
因为是在查看文档的时候，在属性表里有看到 https://spritejs.org/#/zh-cn/api/ext3d/layer3d?id=attributes。我以为在表里的属性都可以这样修改，所以测试了下

**Comment by akira-cn** [comment]
嗯，是这样的，因为layer继承group，而group继承Block，所以那些属性会被带过来，但是layer渲染的时候是不会渲染这些属性的。
