### ISSUE TITLE
如何准确的放置3d模型到layer中，有没有方便的坐标转换方式

### ISSUE THREAD

**Issue by xinde** [spritejs/spritejs#196]
现在的3d坐标是基于webgl的虚拟坐标，没有单位的。
有没有便捷的方式处理坐标问题，比如实现多个3d模型堆叠排列就很需要确切的坐标位置

**Comment by akira-cn** [comment]
具体是什么意思？你的3d模型是什么坐标单位？

**Comment by xinde** [comment]
> 具体是什么意思？你的3d模型是什么坐标单位？

感谢回复。关于3d方面因为是新手，很多还不了解，见谅。
我的意思是，如果我要在示例里的那个狐狸模型背上添加一个cube，如何能快速定位放上去呢，还是说只能一点点试
诸如此类的，多个3d模型堆叠，并行排列，像之前 spritejs 2d，有像素距离就很好计算排列

周末看了一些文章，好像是说如果要精确控制就要对这些 模型坐标，世界坐标，视（观察）坐标，齐次坐标，空间坐标等做一个转换。我再去学习下，叨扰了，谢谢！
