### ISSUE TITLE
能否将 node-canvas 渲染的逻辑独立出来

### ISSUE THREAD

**Issue by AngusFu** [spritejs/spritejs#2]
提一个不成熟的想法。
执行 `npm install` 时因为 node-canvas 的缘故常常失败。况且此种服务端渲染并非通用需求。建议逻辑独立成一个新的项目。

**Comment by akira-cn** [comment]
我把node-canvas依赖去掉吧，本身代码不是很多，但是因为node-canvas依赖需要安装一些其他的依赖项。。
