### ISSUE TITLE
mousedown事件是在鼠标按键弹起时触发的

### ISSUE THREAD

**Issue by RockyF** [spritejs/spritejs#20]
库版本：master分支的dist里的库文件

如题，mousedown事件的回调并没有在鼠标按下时触发，而是在弹起的时候触发了，
紧接着是mouseup事件触发。
是不是有bug？

追加：按下后拖动鼠标，再弹起鼠标，就不会有任何事件触发。

**Comment by akira-cn** [comment]
你好，我测试了一下目前最新的，并没有发现mousedown事件在弹起的时候触发

我写的测试例子在这里：https://code.h5jun.com/xija/edit?js,output

mouseup的触发规则，如果按下鼠标后将鼠标拖出元素区域再松开，元素的mouseup是不会被触发的

你能把有问题的代码贴出来我测试一下吗

多谢

**Comment by RockyF** [comment]
OK，那就是simulator的缘故！
但是如果能统一掉就好了！😝

**Comment by akira-cn** [comment]
不仅是模拟器，就算真正设备的浏览器事件序列也是那样的，这就是webkit浏览器的实现。他们这么实现据说是为了更好的支持surface这类同时支持触屏和鼠标的设备。
