### ISSUE TITLE
3D 图形有没有类似的 ThreeBSP 的几何体布尔运算

### ISSUE THREAD

**Issue by xinde** [spritejs/spritejs#202]
3D 图形有没有类似的 ThreeBSP 的几何体布尔运算哦，想实现类似墙体挖洞填窗户的功能

方法 | 作用
-- | --
intersrct | 交集、重合的部分
union | 并集、组合、相加
subtract | 差集、相减

https://github.com/spritejs/spritejs/issues/145   这个是 2D 图形

https://github.com/sshirokov/ThreeBSP

**Comment by akira-cn** [comment]
这个目前没有
