### ISSUE TITLE
生成的canvas元素，.toDataURL('image/png') 导出的图片空白

### ISSUE THREAD

**Issue by Zion0707** [spritejs/spritejs#209]
用spritejs写的canvas的图像，无法用cavnas.toDataURL('image/png')导出所绘制的canvas图像，导出的png图片为空白。并且使用 cavnas.getContext('2d') 试图获取对象，结果为null，该怎么样才能导出所绘制的图像呢？

**Comment by akira-cn** [comment]
看文档，使用[快照](https://spritejs.org/#/zh-cn/guide/snapshot)

另外如果加载了图片，因为图片是异步加载的，所以需要 `await sprite.textureImageReady`

**Comment by Zion0707** [comment]
好的，谢谢！
