### ISSUE TITLE
makeSmoothCurveLine 单调性如何保证

### ISSUE THREAD

**Issue by xiaobaiha** [spritejs/spritejs#220]
makeSmoothCurveLine目前使用贝塞尔曲线来绘制，如果如果图表图使用了spritejs，在绘制平滑曲线图的时候要如何处理呢

**Comment by akira-cn** [comment]
你能提供一个具体case吗，这样说比较抽象。

**Comment by xiaobaiha** [comment]
https://codesandbox.io/s/upbeat-khorana-pkcs6?file=/src/index.js 我使用qcharts提供了一个demo，可以看到画出曲线在单调性上是有问题的，两点之间会发生先变高再变低，或者先变低再变高。这个是不是使用贝塞尔曲线选取控制点算法的缺陷？

**Comment by akira-cn** [comment]
这个就是贝塞尔曲线平滑的特性，你要保持单调性，要用catmullrom的平滑方式
