### ISSUE TITLE
fillColor 

### ISSUE THREAD

**Issue by EagleWolf** [spritejs/spritejs#222]
fillColor ，如何修改，方向，类似于 linear-gradient(to bottom, red , yellow);

https://jsrun.net/bswKp/edit

现在只能从做到从左到右

**Comment by EagleWolf** [comment]
> _No description provided._

**Comment by akira-cn** [comment]
修改vector就可以呀

**Comment by EagleWolf** [comment]
@akira-cn ,方便修改下代码吗？现在vector: [0, 290, 290, 290],现在是从左到右，修改后，没有达到从下到上的效果，谢谢

**Comment by akira-cn** [comment]
这个例子，改成 `vector: [0, 0, 0, 50],` 就是从上到下效果。

**Comment by EagleWolf** [comment]
非常感谢~可以了
