### ISSUE TITLE
元素都不能绑定右击(contextmenu)事件么？

### ISSUE THREAD

**Issue by jiafeiblog** [spritejs/spritejs#227]

**Comment by jiafeiblog** [comment]
元素绑定不了，Scene上也绑不了...

**Comment by akira-cn** [comment]
文档里有自定义事件的例子，默认scene上只绑定了mouse和touch事件，其他事件可以自己派发一下：

https://spritejs.org/#/zh-cn/guide/events?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e4%ba%8b%e4%bb%b6
