### ISSUE TITLE
请问一下，与 fabric.js有何异同呢？

### ISSUE THREAD

**Issue by hengwangm** [spritejs/spritejs#23]
请问一下，与 fabric.js有何异同呢？

**Comment by akira-cn** [comment]
有很多地方不一样，列举几个

- SpriteJS的API与DOM更加一致，使用D3绘制图表的时候会更加方便，[例子](http://spritejs.org/#/zh-cn/guide/d3)
- 支持标准的Web Animation API，所以熟悉CSS3动画的前端工程师更容易上手使用。
- 方便的Transition API
- ES6+，动画、transition 的 Promise 接口，支持 async/await
- 跨平台性更好，除了支持浏览器、Node还支持微信小程序
