### ISSUE TITLE
请问animate的结束回调事件

### ISSUE THREAD

**Issue by xumjs8623** [spritejs/spritejs#245]
一直在找动画的结束回调事件，好像文档中也没有体现

**Comment by akira-cn** [comment]
animate 返回对象的finished属性是 promise，所以直接用异步就可以。

```js
await sprite.animate(...).finished;
```

你可以看下面这个例子：https://spritejs.org/demo/#/quick_start

**Comment by akira-cn** [comment]
这个是按照 [Web Animations API](https://drafts.csswg.org/web-animations/) 设计的

**Comment by xumjs8623** [comment]
好的 谢谢
