### ISSUE TITLE
borderRadius 大于 50% 。。

### ISSUE THREAD

**Issue by AngusFu** [spritejs/spritejs#25]
提一个不知道是不是 bug 的问题。。。

下面是 DSL：
```
<s-sprite size="400 400" pos="1000 100" border="4 #c7c" border-radius="300"></s-sprite>
```

JS（伪代码？） 大概如下：
```
const sprite = new Sprite()
sprite.size = [400, 400]
sprite.borderRadius = 300
sprite.borderColor = '#c7c'
sprite.borderWitdh = 4
```

结果如下图：

![image](https://user-images.githubusercontent.com/8180186/42376761-efa69b56-8152-11e8-98e0-d848e48ec308.png)

说是问题吧，确实是个问题。。可是严格来说，确实不算 bug，只不过和正常的 DOM & CSS 那一套不太一致而已。。。

**Comment by akira-cn** [comment]
这个算是彩蛋吧23333333，css的最大只到50%

**Comment by AngusFu** [comment]
hmm 哈哈哈哈 其实也挺好看的
