### ISSUE TITLE
添加<!doctype html>后动画无法显示

### ISSUE THREAD

**Issue by kerojiang** [spritejs/spritejs#250]
在html中添加<!doctype html>后，所有的动画都无法显示了，但是没有任何报错，调试了一下，所有的相关对象创建都正常,去掉<!doctype html>后一切正常,不知道为啥会这样
spritejs版本3.7.36

**Comment by akira-cn** [comment]
这个应该是其他问题引起的吧，你看官方例子 https://spritejs.org/demo/#/quick_start，这里的主页面和iframe页面里面也都有`<!doctype html>`的声明，并不会对动画造成什么影响。
