### ISSUE TITLE
安卓上雪碧图做帧动画卡顿问题

### ISSUE THREAD

**Issue by zhangmin173** [spritejs/spritejs#26]
ios和pc流畅，安卓卡顿。有什么解决方案吗？

**Comment by zhangmin173** [comment]
bg.animate([
            { textures: { src: 'bg', srcRect: [0, 0 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [750, 0 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [1500, 0 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [2250, 0 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [3000, 0 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [3750, 0 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [4500, 0 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [5250, 0 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [6000, 0 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [6750, 0 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [0, 1334 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [750, 1334 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [1500, 1334 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [2250, 1334 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [3000, 1334 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [3750, 1334 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [4500, 1334 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [5250, 1334 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [6000, 1334 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [6750, 1334 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [750, 2668 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [1500, 2668 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [2250, 2668 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [3000, 2668 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [3750, 2668 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [4500, 2668 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [5250, 2668 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [6000, 2668 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [6750, 2668 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [0, 4002 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [750, 4002 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [1500, 4002 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [2250, 4002 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [3000, 4002 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [3750, 4002 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [4500, 4002 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [5250, 4002 + 100, 750, 1334] } },
            { textures: { src: 'bg', srcRect: [6000, 4002 + 100, 750, 1334] } }
        ], {
                duration: 1500,
                fill: 'both'
            });

**Comment by akira-cn** [comment]
把 easing 设置成 'step-end' 试试？

**Comment by zhangmin173** [comment]
文档上关于这方面的描述感觉不多，希望可以补上。

目前我把每帧图片用单图来加载，效果会提升把？

**Comment by akira-cn** [comment]
是的，帧动画单张图加载会触发缓存，理论上性能更好。
