### ISSUE TITLE
请问SpriteJS V3 如何自定义元素，需要重写那些方法？

### ISSUE THREAD

**Issue by Joy818** [spritejs/spritejs#263]
SpriteJS V2 可以以通过重写render 实现元素自定义
请问 SpriteJS V3 如何实现自定义，需要重写哪些方法，有没有示例或者文档?

**Comment by Joy818** [comment]
期望可以实现[V2文档](https://www.bookstack.cn/read/spritejs-v2/05a87c82d7b0831b.md )中的效果，可以自定义属性，绘制时根据属性值的不同，绘制不同的内容

我在v3中看到有个draw方法，其参数是meshes,我尝重写该方法，在放方法中自定义mesh交给父类方法进行绘制，但好像没有什么作用。

下面是我自定义的类

```javascript
class MySpriate extends spritejs.Sprite {
  constructor() {
    super({
      size: [500, 500],
    })
  }
  draw(meshes) {
    // super.draw([mesh1, mesh2])
    const figure = new Figure2D()
    figure.rect(0, 0, 200, 200)

    const mesh1 = new Mesh2D(figure)
    mesh1.setFill({
      color: [1, 0, 0, 0.5],
    })

    const mesh2 = new Mesh2D(figure)
    mesh2.setFill({
      color: [0, 0, 1, 0.5],
    })

    return super.draw([mesh1, mesh2])
  }
}

```

**Comment by akira-cn** [comment]
v3和v2的机制不一样，v3是webgl渲染，因为要做同类材质的元素合并，这样才能最大限度减少draw call，提升性能，所以不建议用户重写绘制方法，那样的话引擎无法判断要做何种优化，你可以看一下具体需求能不能通过重写着色器来实现。

**Comment by Joy818** [comment]
> 

好的，感谢
