### ISSUE TITLE
请问下：实例化多个 Path, 并且每个 Path 的 点位有几千个，通过 layer.append 批量添加，会导致卡顿，这种情况下要怎么处理呢？

### ISSUE THREAD

**Issue by magicLaLa** [spritejs/spritejs#270]
![image](https://user-images.githubusercontent.com/23513387/197092494-215e35f8-8c87-4767-afb3-d47e4a381ebd.png)

看效果是 按批量绘制，最后一次性画上去的😂，然后我设置了 layer 的 bufferSize 还是一样的，因为想要一起显示出来，不想按批次渲染

**Comment by akira-cn** [comment]
顶点太多肯定会卡的，因为创建Path的时候要动态计算轮廓和做三角剖分，这个在框架设计上没法避免。如果Path形状是固定的，可以先离线算好mesh，手工创建mesh2d对象，自定义一个类似Path的类，把离线算好的mesh2d对象添加上去。如果Path形状是动态计算的，那就没有特别好的办法。

**Comment by magicLaLa** [comment]
> 



> 顶点太多肯定会卡的，因为创建Path的时候要动态计算轮廓和做三角剖分，这个在框架设计上没法避免。如果Path形状是固定的，可以先离线算好mesh，手工创建mesh2d对象，自定义一个类似Path的类，把离线算好的mesh2d对象添加上去。如果Path形状是动态计算的，那就没有特别好的办法。

好的，感谢。
