### ISSUE TITLE
sprite.js label标签在win11上渲染异常

### ISSUE THREAD

**Issue by Thever** [spritejs/spritejs#276]
问题：
sprite.js label标签在win11上渲染异常，同样代码在win7,win10上渲染正常

<img width="580" alt="issue" src="https://github.com/spritejs/spritejs/assets/15309403/3fee7ee4-b9e1-4cfa-b730-ccc9cd82e834">

测试环境：
Windows11 家庭版，22H2, 操作系统版本22621.1848
Windows11 家庭版，21H2, 操作系统版本22000.1936

Chrome 114.0.5735.199（正式版本） （64 位）
Edge 114.0.1823.67 (正式版本) (64 位)

使用了一下方法尝试修复均失败：
1.scence 设置  
  powerPreference: 'high-performance'， bufferSize: 1500000
2.label 设置
  fontFamily：‘sans-serif’，取消字体宽高
3.异步延迟渲染Label

猜想：查询网络发现win11上渲染存在问题，是否是因为系统自身问题导致的？

**Comment by akira-cn** [comment]
不清楚是否是windows或者edge环境问题，你如果换浏览器可以正常渲染吗？

**Comment by Thever** [comment]
firfox 115.0 (64 位)上是可以正常显示的，我刚刚调整了label的lineheight,width和height,有的时候渲染正常，有时字体就会被切片或者扭曲渲染异常了，这个可能和浏览器有关系？
用原生canvas用 strokeText 设置相关属性渲染本地是正常的，会不会有什么底层的东西我没考虑到？

**Comment by Thever** [comment]
补充：
官方文档 label 说明在chrome和edge浏览器中也存在渲染瑕疵([http://spritejs.com/#/zh-cn/block?id=%e6%96%87%e5%ad%97-label](http://spritejs.com/#/zh-cn/block?id=%e6%96%87%e5%ad%97-label))

这里有一些截图方面查看：
Chrome 114.0.5735.199（正式版本） （64 位）
<img width="667" alt="chrome" src="https://github.com/spritejs/spritejs/assets/15309403/2a320c2d-3c8e-4694-b179-815d000ceebc">

Edge 114.0.1823.67 (正式版本) (64 位)
<img width="667" alt="edge" src="https://github.com/spritejs/spritejs/assets/15309403/3d0a0eb3-0534-4e3c-8370-ba1e376dadbe">

firfox 115.0 (64 位)
<img width="646" alt="firefox" src="https://github.com/spritejs/spritejs/assets/15309403/ee640809-2c9b-4bfb-8c66-33a6750cb54d">

得空了请您看下，谢谢

**Comment by akira-cn** [comment]
我的mac电脑上都没有问题，我没有windows环境，label渲染是用2D渲染之后再把内容绘制到webgl上的，确实不明白这块为啥会有问题。。有可能要用SDF绘制字体比较好，但是这需要比较大的建模工作量，现在短期估计实现不了。你的应用是不是固定文字的，看起来好像你只是显示一些字母和阿拉伯数字，你可以考虑换成bmfont方案，把英文和数字转成图片，然后用图替代label

**Comment by Thever** [comment]
嗯，为了兼容性我PS了D1到D24的图片替换Label，可以正常展示，先当临时过渡方案保证效果了。感谢您百忙之中抽空回复~

**Comment by LiGaoLiang7** [comment]
![微信截图_20240425112710](https://github.com/spritejs/spritejs/assets/16475699/4490339e-d220-4b00-83e7-891aef62a6ea)
官网这个例子在Win11系统中label显示有问题，鼠标划过文字就正常了，https://spritejs.com/demo/#/transforms
可以在代码中用定时器用重新设置一下label的颜色，显示就能正常
