### ISSUE TITLE
是否支持rotate3d，perspective等3d变换

### ISSUE THREAD

**Issue by Crazz-Joe** [spritejs/spritejs#28]
看到attrjs源码里只有translate、rotate、scale、skew、和matrix的2d变换，那么像rotate3d、translate3d、skew3d、perspective等或者rotateX，translateY等该如何实现，是只能引入threejs这样的库吗

**Comment by akira-cn** [comment]
现在spritejs是2d库，3d是不支持的，rotateX和translateX支持，因为rotate和translate的值是数组[x, y]

**Comment by Crazz-Joe** [comment]
rotateX，rotateY也是不支持的吧，我看attrjs里rotate参数只有一个是控制z轴的

**Comment by Crazz-Joe** [comment]
还有个问题，就是与css3 keyframe渲染不一致的问题，同样的参数下
`@keyframes imgCustom1524134370590 { 
   0% { transform: translateX(0px) translateY(0px)} 
   20% { transform: translateX(0px) translateY(50px}
   40% { transform: translateX(0px) translateY(100px}
   60% { transform: translateX(0px) translateY(150px)} 
   80% { transform: translateX(0px) translateY(200px)} 
   100% { transform: translateX(0px) translateY(0px)} 
}`
和spirtejs
` el.animate([
         { translate: [0, 0], offset: 0},
         { translate: [0, -50], offset: 0.2 },
         { translate: [0, -100], offset: 0.4 },
         { translate: [0, -150], offset: 0.6 },
         { translate: [0, -200], offset: 0.8 },
         { translate: [0, 0], offset: 1 },
], {
     duration: 5000,
     fill: "both",
     easing: "ease"
})`
两者的实际效果不一致，css3会根据百分比断断续续的上移，而spritejs则仿佛offset没有效果一样，直上直下的移动

**Comment by akira-cn** [comment]
https://code.h5jun.com/vebi/edit?html,css,output

**Comment by akira-cn** [comment]
我知道你的意思了，SpriteJS的动画标准是[Web Animation Api](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Using_the_Web_Animations_API)

这个本来就和css3的keyframes是不一样的

https://code.h5jun.com/yunuy/edit?html,css,js,output

你可以看这个例子，这是原生的web animation api的效果，和spriteJS一直，和css3的keyframes-animation是不一致的

**Comment by Crazz-Joe** [comment]
我知道原因了，web animation api 是支持给每一段keyframe配置easing属性的，而spriejs是不支持的，
https://code.h5jun.com/pizi/edit?html,css,js,output 这个demo我试着给每一个关键帧都加上了easing参数然后效果就和css3 keyframe的效果是一样的了，看样子默认情况下css3 keyframe是将easing应用在了每一个关键帧上，每个关键帧动画都重新计算easing而web animation api是默认easing在这个动画区间生效，需要手动指定在每个关键帧内的easing才能应用到每一帧上，所以。。。这里是spritejs与web animation api 有点出入啊， 是不是可以考虑加一下在每一帧上配置easing呢

**Comment by Crazz-Joe** [comment]
赞

**Comment by akira-cn** [comment]
已经加上啦
