### ISSUE TITLE
中文文档中例子链接访问时会不断重定向

### ISSUE THREAD

**Issue by liulinboyi** [spritejs/spritejs#280]
此处更换了中文文档例子的地址，刚才访问时此链接会不断重定向
https://github.com/spritejs/spritejs/blob/78008a803ae2f61070dc720e15cfc42fc823463a/docs/zh-cn/_navbar.md?plain=1#L14

![image](https://github.com/spritejs/spritejs/assets/41336612/44107a1a-a8bb-4f8d-8064-9975d3fdac34)

临时暂解决办法是切换到[英文版](https://spritejs.com/#/en/index)，再点击例子就是[原来的网址](https://spritejs.com/demo/#/quick_start)了。

**Comment by akira-cn** [comment]
这个我换回去吧。。。

**Comment by liulinboyi** [comment]
> 这个我换回去吧。。。

ok
