### ISSUE TITLE
如何将代码拆分成多个js引用？

### ISSUE THREAD

**Issue by alexxxcs1** [spritejs/spritejs#29]
比如我写了一个load.js，里面是预加载，但是预加载完成的texture数据我不知道存在哪里，只能在异步function里面使用吗？我能不能在layer里面拿到这些加载完成的数据？

**Comment by alexxxcs1** [comment]
找到解决方案了，通过load 的异步加载，最终触发开始界面

**Comment by akira-cn** [comment]
预加载其实可以直接使用spritejs的scene.preload，文档在[这里](http://spritejs.org/#/zh-cn/guide/resource)

scene.preload不但能预加载texture，还支持texturePacker
