### ISSUE TITLE
Issue on accuracy(?) with official D3 demo

### ISSUE THREAD

**Issue by AngusFu** [spritejs/spritejs#30]
反馈下官网 D3 demo 中的一些细节 ——

链接：[官网 D3 demo](http://spritejs.org/#/zh-cn/guide/d3)

原因：未知。（performance？bug？accuracy issue？）

## example 01

鼠标快速移动时，从外部进入靠近边缘的圆圈，出现如下现象（问题：城市选中而省份却没选中）：

<img width="708" alt="default" src="https://user-images.githubusercontent.com/8180186/43473685-6a858ede-9523-11e8-9935-e0e8bc27e1d2.png">

<img width="667" alt="default" src="https://user-images.githubusercontent.com/8180186/43473713-81cb77b6-9523-11e8-8f6b-6014f7f34fd3.png">

## example 02 

操作路径：空白 -> 甘肃 -> 武威 -> （停留一阵）-> (常规速度移动) 哈尔滨 -> 牡丹江 -> 浙江绍兴

<img width="653" alt="default" src="https://user-images.githubusercontent.com/8180186/43473967-157c2ee2-9524-11e8-840b-446f318b4c61.png">

## example 03

操作方式：Mac 下选中江苏，然后滑动到另外一屏，接着滑回到页面移动鼠标至另一省份，如是操作再三即可出现类似如下效果。

<img width="688" alt="default" src="https://user-images.githubusercontent.com/8180186/43474366-428ebbf6-9525-11e8-8cc5-d7ca08be97a6.png">

**Comment by akira-cn** [comment]
是bug，修改了事件触发机制导致的，多谢反馈

**Comment by akira-cn** [comment]
已修复
