### ISSUE TITLE
发现一个bug，元素的滤镜-blur不能和属性-rotate及属性-shadow共存

### ISSUE THREAD

**Issue by alexxxcs1** [spritejs/spritejs#31]
`a2.attr({
            rotate:10,
            filter:{
                blur:'10px'
            },
            shadow: {
              },
});`

这样的话元素会消失，只看得到到阴影。

**Comment by akira-cn** [comment]
这个有可能是canvas的机制（或bug?），shadow和fiter一起用会导致tranform两倍，你看这个原生canvas的例子： https://code.h5jun.com/pemo/edit?html,output

**Comment by alexxxcs1** [comment]
@akira-cn 好像不是哦，我又看了一下，只有rotate，filter，shadow三个一起存在元素才会消失，任意两个组合是可以正常显示的，

**Comment by akira-cn** [comment]
消失是因为filter和shadow造成了2倍的rotate，把元素转出所在的cacheContext了，因为spritejs的渲染机制是在元素有filter或shadow的时候会创建一个小的canvas绘制元素，然后设置filter和shadow，最后再把元素绘制到外层大的canvas上，但是因为filte和shadow一起用造成了额外的transform，结果cacheContext被意外移出了可视区域。。。

你可以先设置一个小一点的rotate测一测，就知道了。

**Comment by alexxxcs1** [comment]
@akira-cn 哦！好像是的，之前因为放在group里，移出了可视区域就看不到了。现在看到了，是旋转到其他地方去了，我还有一个问题，我就不另开issues了。
就是 , animate的finished是Promise对象吧? await animate.finished一直不会结束，animate.finished一直是pendding状态，然后我看官方示例里面那个好像也出错了。
http://spritejs.org/#/zh-cn/doc/animation?id=spriteanimate

**Comment by alexxxcs1** [comment]
@akira-cn 哦！好像是的，之前因为放在group里，移出了可视区域就看不到了。现在看到了，是旋转到其他地方去了，我还有一个问题，我就不另开issues了。
就是 , animate的finished是Promise对象吧? await animate.finished一直不会结束，animate.finished一直是pendding状态，然后我看官方示例里面那个好像也出错了。
http://spritejs.org/#/zh-cn/doc/animation?id=spriteanimate

**Comment by alexxxcs1** [comment]
@akira-cn 我是说三个小圆点的那个
await s1.animate([
    {scale: [1, 1]},
    {scale: [0.8, 0.8]},
    {scale: [1, 1]},
  ], {
    duration: 1000,
  }).finished
  await s2.animate([
    {scale: [1, 1]},
    {scale: [0.8, 0.8]},
    {scale: [1, 1]},
  ], {
    duration: 1000,
  }).finished
  await s3.animate([
    {scale: [1, 1]},
    {scale: [0.8, 0.8]},
    {scale: [1, 1]},
  ], {
    duration: 1000,
  }).finished

这个他没有设置iterations啊，看代码这个效果应该是第一个小圆点动完第二个小圆点动，再第三个动，可是示例里好像都没有动，不知道是不是我这里浏览器的问题，我自己的话，我也知道设置Infinity是不会触发finished的，所以我没有设置iterations，难道默认不是1吗？
不知道你哪里看到官网的示例是咋样的，我这里好像看不到效果。

然后还有就是，group里面的元素的animate设置了playbackRate是没有效果的吗？只能是在layer上的元素playbackRate才有效果吗？
我的版本是 "spritejs": "^2.5.1" 
还有好像animate的配置设置完以后就是静态的了，如果我把配置的playbackRate = 变量的话，变量改变，animate的playbackRate是不是不会跟着改变？这样的话，需要我在requestAnimationFrame里面手动修改是吗？

**Comment by akira-cn** [comment]
那个例子是好的，最近codepen抽风，用了await的代码embed的时候会有问题，报generatorRuntime is not defined，你直接右上角链接点过去是好的 https://codepen.io/akira-cn/pen/KebpYp

group并没有单独的timeline，所以设置不了group的timeline，目前只支持设置和修改layer的timeline来批量改变动画的速度。变量改变当然不会改变playbackRate，那个是传值，你需要重新给playbackRate赋值

**Comment by alexxxcs1** [comment]
@akira-cn 我知道了，谢谢，用这个框架在学ES6，感觉不错，希望继续改进
