### ISSUE TITLE
文档错别字

### ISSUE THREAD

**Issue by hb-bobo** [spritejs/spritejs#33]
[传送门](https://github.com/spritejs/spritejs/blob/6bc425050d62130a72c82374097f3aff7afbb03e/docs/zh-cn/doc/layer.md)

toGolbalPos() -> toGlobalPos();

另外
以后能不能加一个canvas 自己传进去，现在react,vue，自己传的情况多一点吧

**Comment by akira-cn** [comment]
多谢，修复了，canvas是可以将自己的Context传给Layer的，只是文档里暂时没写。

```js
const scene = new Scene('#container', width, height);
const context = document.getElementById('mycanvas').getContext('2d');

const fglayer = scene.layer('fglayer', {context});

fglayer ...
```

**Comment by hb-bobo** [comment]
@akira-cn  感谢解答, 我竟然没发现
