### ISSUE TITLE
不同group里面的sprite不能使用OBBCollision检测碰撞

### ISSUE THREAD

**Issue by MTTTM** [spritejs/spritejs#34]
**问题：**
一个group里面的子弹sprite和另外一个group里面的怪物sprite碰撞了但是没有检测到
**疑惑：**
我需要做什么额外的配置么
还是不同group里面的sprite不能检测碰撞
**感谢：**
期待回复，非常谢谢。

**源码**
**bullet.js(子弹):**
const grenade = new Sprite();
export { grendeInit, PNG, JSON, grenade, shoot };

**Grenade.js（人物和子弹放到一个group）:**
import {grendeInit as bulltInit, PNG as bulltPng,JSON as bulltJSON,grenade as bulltGrenade,shoot as bulltShoot} from "../bullet/bullet.js"

const group = new Group();
const grenade = new Sprite();

 group.append(grenade); //添加人物
   group.append(bulltGrenade); //添加子弹

export { grendeInit, grenadePNG,grenadeJSON,grenade,shoot,group,bulltGrenade};

**group.js（组合页面）:**
 import { grendeInit, grenadePNG, grenadeJSON,grenade,shoot,  group as ggroup,bulltGrenade} from "./group/Grenade.js";;

//...
const scene = new Scene(  ....
//...
     const layer = scene.layer();
     const group = new Group();  //包含怪物一个分组
 //...
    group.append(abcd);
     layer.append(group);
     layer.append(ggroup);  //ggroup是包含子弹和人物的另外一个分组

//碰撞检测=======
const collision = function(obj, obj2) {
         if (obj.OBBCollision(obj2)) {
         	 console.log("中枪！疼!")
            
         }
    
 }
layer.on('update', (evt) => {
      //检测子弹和怪物abcd的碰撞
         collision(bulltGrenade,abcd);
 });

**Comment by akira-cn** [comment]
不同group之间目前的确是没法这么检测的，因为参考位置不一样，如果重新计算的话，我担心性能问题，所以目前不支持，我想一下这个情况怎么解决，可能会在下一个版本里解决。
