### ISSUE TITLE
IE内核下，只能渲染，交互事件无效

### ISSUE THREAD

**Issue by ghost** [spritejs/spritejs#36]
Chrome浏览器下正常，但IE下，只能让内容渲染出来，但是无法触发点击，移入移出的事件。是本来就不考虑IE，还是我需要再配置哪些插件。

**Comment by akira-cn** [comment]
IE多少版本的？IE11以下可能都会有问题。我们现在没有考虑IE，也没有在IE下测试。如果能把问题描述再清晰一些，如果发现问题能帮忙修的话，可以给我们提PR，我们会非常感谢。

**Comment by akira-cn** [comment]
IE多少版本的？IE11以下可能都会有问题。我们现在没有考虑IE，也没有在IE下测试。如果能把问题描述再清晰一些，有具体case，我们可以case by case修复。如果发现问题能帮忙修的话，可以给我们提PR，我们会非常感谢。
