### ISSUE TITLE
请问预加载最大加载时间怎么设置？

### ISSUE THREAD

**Issue by alexxxcs1** [spritejs/spritejs#37]
有个项目要加载很多图片，所以加载了30秒后出现了
`
Uncaught (in promise) Error: load img timeout
`

于是我找到了 node_modules\spritejs\lib\resource.js 里面修改了 var timeout = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 30000;的时长，但是这样的话不是一个很好的解决办法，所以我再应用层该怎么设置。

**Comment by akira-cn** [comment]
这里我给改一下吧，给加一个全局的配置，Resource.loadTimeout 吧，默认值 30 秒，可以修改，比如

```js
spritejs.Resource.loadTimeout = 180000;
```

2.12 版本更新。
