### ISSUE TITLE
sprite update 事件

### ISSUE THREAD

**Issue by duhongwei** [spritejs/spritejs#39]
sprite.on('update', (evt) => {
  rangeBar.value = animation.progress * 100
})

如果在evt中直接包含 progress 或者  animation.progress 或者  animation  ，从使用的角度来说，会更方便。

**Comment by akira-cn** [comment]
这个我们考虑一下。主要是现在sprite对象并不持有animation引用，如果持有的话，就要管理这些引用并在animation结束的时候释放掉这个引用

**Comment by duhongwei** [comment]
如果要考虑的话，transition 也考虑下吧。
let transition = button.transition(0.5)
button.on('mouseenter', (evt) => {
   //这块写成 this.transition 感觉好些。上面的animation也一样，放在sprite上比放事件参数里好。
   transition.attr({
    bgcolor: '#666',
    fillColor: '#fff',
  })
})

**Comment by akira-cn** [comment]
一个sprite的transition和animation同时允许有多个实例的，因为同时可能会有不同属性的多段动画或transition，如果需要某个实例的话还是自己存一下吧
