### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by JessyYang** [spritejs/spritejs#40]
运行命令 npm test,32 passed,1 failed.报错信息如下：
<img width="672" alt="2018-09-05 4 16 36" src="https://user-images.githubusercontent.com/18657019/45080528-aa12cd80-b127-11e8-86fe-cd2d3b332b64.png">

**Comment by akira-cn** [comment]
这个case可能是因为网络问题，远程图片没能加载下来。。

我这边是OK的，然后CI状态也是passing，应该是没问题的
