### ISSUE TITLE
webpack引入后build报错

### ISSUE THREAD

**Issue by hcxw11** [spritejs/spritejs#42]
使用`yarn add spritejs`引入
使用`yarn start`能正常使用
使用`yarn build`报错
```
yarn run v1.3.2
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/spritejs/src/spritejs.esm.js:7

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
是否能改为es5的编译版本？

**Comment by akira-cn** [comment]
你可以把 ./script/build.js 里面的 buildTask({esnext: true}); 这条编译命令注释掉，这样就不会编译es6的版本了。

**Comment by hcxw11** [comment]
@akira-cn 谢谢月影大大，如果按照这种方式改的话是不是要修改node_modules里面的代码，重新每次下载依赖的时候都要去修改配置（最后还是使用了js标签）

**Comment by akira-cn** [comment]
哦，你是说在自己项目里面作为依赖编译？
因为package.json的module配置了的关系，所以默认走了spritejs.esm.js。
如果用webpack，你可以直接配一下alias到node_modules/spritejs/dist/spritejs.js
如果用rollup，似乎也是有类似的配置？
