### ISSUE TITLE
animate.timeline.currentTime =0 出现报错

### ISSUE THREAD

**Issue by MTTTM** [spritejs/spritejs#43]
//代码如下：
 if (!this.walk.animate) {
            //没有调用过的时候
            var a = (0, _index.walk)();
            this.walk.animate = this.animate(a.frame, a.opt);
            this.currentStatus = Object.assign(this.currentStatus, this.STATUS.walk, { type: "walk" });
        } else if (this.walk.animate && this.walk.animate.playState !== "running") {
            //  console.log("pase!!!!!!!!")
            //调用过，并且已经停止
            this.walk.animate.timeline.currentTime = 0;//报错的行
            this.walk.animate.pause(); //必须pause后才能play   ;;;
            this.walk.animate.play();
            this.currentStatus = Object.assign(this.currentStatus, this.STATUS.walk, { type: "walk" });
 }

报错如下：
Uncaught TypeError: Cannot read property 'resolve' of undefined
    at (anonymous function).reverseTimerID.timeline.setTimeout.delay (http://localhost:3000/static/js/spritejs.js:3761:34)
    at spritejs.js:667
    at Array.forEach (<anonymous>)
    at Timeline.set (spritejs.js:651)
    at Sprite.walk (tree.js:840)
    at Object.Action (tree.js:2606)
    at Object.parallel (tree.js:2562)
    at Object.Sequence (tree.js:2545)
    at Object.probability (tree.js:2588)
    at Object.Filter (tree.js:2650)

请问这个是什么原因，我经常会遇到这个问题。但是不知道是什么回事

**Comment by akira-cn** [comment]
你好，你能告诉我使用的是哪个版本的问题吗？只是这些信息是没法定位的。如果你有造成问题的可运行的完整代码，麻烦贴完整代码上来。

**Comment by MTTTM** [comment]
在线访问（一个月后失效）：https://w3cplus.gitee.io/spritejs/tree.html
谷歌浏览器打开移动模拟器容易出现错误（2秒内）

另外：修改其中一个精灵（dog）的zindex，会导致另外一个（hero）精灵抖动（两个精灵在同一个组里面）


程序入口：https://gitee.com/w3cplus/spriteJS/blob/master/demo/src/js/entry/tree.js
             如果新增一个dog（恢复66行的注析以及265行）会导致新增加的dog直接sb掉，卡。
报错源码（199行）：https://gitee.com/w3cplus/spriteJS/blob/master/demo/src/js/tree/dog/index.js

项目启动命令： gulp browser


这是我学习小游戏的第一个demo，可能代码会有点乱，如果你感兴趣的话，期待帮忙查看下。谢谢

**Comment by akira-cn** [comment]
这个timer的问题我已经修复了，升级到2.15.4即可

其他问题我再查一下
