### ISSUE TITLE
npm install spritejs 后报错 ReferenceError: Unknown plugin "transform-runtime" 

### ISSUE THREAD

**Issue by SuperShan0926** [spritejs/spritejs#45]

**Comment by akira-cn** [comment]
如果你的项目里面需要build spritejs的代码，需要安装一下babel-transform-runtime

**Comment by SuperShan0926** [comment]
并不是编译，只是我项目中要用这个，install以后import进来就报这个错

**Comment by akira-cn** [comment]
因为你 import 默认走的是es module，所以会载入 index.esm.js，这样的话也是需要安装 babel 依赖的
如果你要用编译后的版本，你试试直接 import spritejs from 'spritejs/dist/spritejs' 引入编译后的版本
