### ISSUE TITLE
在vue-cli3中使用，打包以后，安卓无法使用，ios无法正常使用

### ISSUE THREAD

**Issue by highmind** [spritejs/spritejs#49]
貌似是因为 默认 import 引入的是 es6版本，不是 编译完的版本，请问，这样的话，babel需要如何配置，安装哪些插件，才能在vue中使用sprite.js

**Comment by akira-cn** [comment]
如果是vue-cli3的话，你可以直接使用[sprite-vue](https://github.com/spritejs/sprite-vue)

文档在这里：http://vue.spritejs.org/

这个打包就没有问题，而且sprite-vue提供了vue runtime的支持，而且可以和你的项目中的其他vue组件兼容，只要将 `import Vue from 'vue'` 替换成 `import {Vue} from 'sprite-vue'`即可

如果你不想用sprite-vue，或者因为版本关系不能用sprite-vue，那么你可以修改一下build/webpack.base.conf.js，配置spritejs使用es5版本：

```js
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      // 'vue$': 'vue/dist/vue.esm.js',
      'spritejs': 'spritejs/dist/spritejs.js',
      '@': resolve('src'),
    }
  },
```

**Comment by highmind** [comment]
多谢大神指导
