### ISSUE TITLE
通过 layer.timeline 控制动画时， Group 的效果有问题

### ISSUE THREAD

**Issue by AngusFu** [spritejs/spritejs#5]
#### 问题
为 layer 设置 `layer.timeline.playbackRate = 0`  后，其中的 Group 动画以及 group 中的 sprites 动画并未停止。

#### 预期
设置 `layer.timeline.playbackRate = 0`  后， group 自身动画以及 group 中的 sprites 动画应该都停下来。

#### demo
https://code.h5jun.com/vesif

**Comment by akira-cn** [comment]
因为sprite拿parent的timeline，group里面的sprite拿到的parent是group而不是layer，所以拿不到layer的timeline，这块v1.15.1已经修复了，应该要总是拿layer的timeline。
