### ISSUE TITLE
demo很多都有问题，跑不起来

### ISSUE THREAD

**Issue by DualWield** [spritejs/spritejs#50]
http://spritejs.org/demo/#animations

http://spritejs.org/demo/#events 无法用wasd键盘控制飞行

**Comment by akira-cn** [comment]
已经修复了

**Comment by DualWield** [comment]
@akira-cn 方向d 仍然是坏的

**Comment by akira-cn** [comment]
keyup有问题我修好了，要先让canvas获得焦点然后按键盘就行了

**Comment by DualWield** [comment]
我是canvas获取焦点后再按键的，除了d方向，其他的都是好的。
而且我看了一下代码，找不到哪里问题，就感觉库可能不太靠谱
