### ISSUE TITLE
layer 配置了{autoRender:false}之后，其父scene调用snapshot一直显示为pendding

### ISSUE THREAD

**Issue by tangxiangmin** [spritejs/spritejs#51]
首先感谢spritejs这个框架，目前已经写了两个比较有趣的项目了。

```js
const scrawlLayer = this.scene.layer('scrawl', {autoRender: false});
// do something

this.scene.snapshot().then(res=>{
  // never run here
}).catch(e=>{
  // never run here too
})
```
这是在项目中偶然发现的，发现移除改配置或者在截图前移除该layer后，才可截图成功，具体bug原因等我这两天忙完了再看下

**Comment by akira-cn** [comment]
你配置了layer的autoRender是false的话，就要在snapshot之后自己手工调用一下layer.draw，否则snapshot截屏不了，因为snapshot需要等待layer绘制完成。

```js
const scrawlLayer = this.scene.layer('scrawl', {autoRender: false});
// do something

this.scene.snapshot().then(res=>{
  // never run here
}).catch(e=>{
  // never run here too
})

scrawLayer.draw(); //这样就可以了
```

**Comment by tangxiangmin** [comment]
> 你配置了layer的autoRender是false的话，就要在snapshot之后自己手工调用一下layer.draw，否则snapshot截屏不了，因为snapshot需要等待layer绘制完成。
> 
> ```js
> const scrawlLayer = this.scene.layer('scrawl', {autoRender: false});
> // do something
> 
> this.scene.snapshot().then(res=>{
>   // never run here
> }).catch(e=>{
>   // never run here too
> })
> 
> scrawLayer.draw(); //这样就可以了
> ```

嗯嗯，谢谢你的回复
