### ISSUE TITLE
事件侦听应该支持this上下文传入,类似eventemitter

### ISSUE THREAD

**Issue by chenweiqun** [spritejs/spritejs#53]
如题

**Comment by akira-cn** [comment]
事件侦听支持传this的使用场景是什么？直接用bind解决不行吗？

**Comment by chenweiqun** [comment]
是的,这在大部分情况下是可以的,可是如果需要移除这个事件的侦听的时候,那么bind返回的函数引用就需要自己存起来,比较麻烦

**Comment by chenweiqun** [comment]
抱歉,我使用的库好像是eventemitter3这个库,它是可以支持的,我的意思是上下文传入是可选的,并不是必须的,其实我遇到的情况是都是基于class去写的,建议参考一下游戏框架egret
