### ISSUE TITLE
安卓报错

### ISSUE THREAD

**Issue by Hardcore0331** [spritejs/spritejs#61]
安卓内使用：
import {
    Scene,
    Sprite,
    Group
} from 'spritejs';
引入后，页面会报错：
SyntaxError: Unexpected identifier

**Comment by akira-cn** [comment]
android肯定不能用import from啊。。。现在android浏览器都还不支持jsm。

你直接引用js文件

```html
<script src="https://unpkg.com/spritejs/dist/spritejs.min.js"></script>
```

然后

```js
const {Scene, Sprite, Group} = spritejs;
```

**Comment by Hardcore0331** [comment]
好的，多谢
