### ISSUE TITLE
如何始终以横屏模式显示？

### ISSUE THREAD

**Issue by HuarenYu** [spritejs/spritejs#63]
请问能不能始终以横屏模式展示呢？就是不管横屏还是竖屏，始终以最大边为宽，最小边为高

**Comment by akira-cn** [comment]
这个恐怕要自己处理一下。可以通过浏览器的 orientation 值来改变 container 的 css-transform，这样就可以始终横屏或竖屏了。

**Comment by HuarenYu** [comment]
> 这个恐怕要自己处理一下。可以通过浏览器的 orientation 值来改变 container 的 css-transform，这样就可以始终横屏或竖屏了。

好的谢谢
