### ISSUE TITLE
如何检验enableCache是否生效以及其作用？

### ISSUE THREAD

**Issue by mysisi** [spritejs/spritejs#66]
一个sprite的实例在不断的attr过程中，内存会一直膨胀，在2.16版本看到增加了enableCache属性，想问这个属性可以解决这个问题么？

**Comment by akira-cn** [comment]
内存不断膨胀不应该啊，可否给一个case我看看，正常情况下设置属性并不会导致内存一直增加的，这个和cache无关。

至于2.16加了enableCache是因为我调整了缓存策略，默认禁止了label和path的缓存。
