### ISSUE TITLE
请问sprite有canvas原生的lineto的打包方法吗？

### ISSUE THREAD

**Issue by alexxxcs1** [spritejs/spritejs#69]
有个项目要做画板，但是好像没有发现lineto 这样的东西。
或者有没有办法暴露canvas的 dom，用原生写法完成，然后再用sprite补充其他功能？

**Comment by akira-cn** [comment]
canvas对象可以通过 layer.context 拿到，然后你可以用[自定义ticker](http://spritejs.org/#/zh-cn/guide/ticker)来托管layer的绘制，这样就可以混用原生api和sprite。

具体你可以看[这个例子](https://code.h5jun.com/nahi/edit?css,js,output)

你也可以通过 beforedraw、afterdraw 事件来处理自定义绘制，文档在[这里](http://spritejs.org/#/zh-cn/guide/events?id=%E5%85%83%E7%B4%A0%E5%92%8C%E7%BB%98%E5%9B%BE%E4%BA%8B%E4%BB%B6)

不知道以上能否解决你的问题，如还有疑问，欢迎随时交流。

**Comment by akira-cn** [comment]
那样的话，你可以使用[扩展库](https://github.com/spritejs/sprite-extend-shapes)

或者继承sprite类型[自定义元素](http://spritejs.org/#/zh-cn/guide/nodes)

**Comment by alexxxcs1** [comment]
> 那样的话，你可以使用[扩展库](https://github.com/spritejs/sprite-extend-shapes)
> 
> 或者继承sprite类型[自定义元素](http://spritejs.org/#/zh-cn/guide/nodes)

我找了另一个方法，就是用canvas原生api画线，然后每一步的touchend把该canvans生成的base64存起来，另外调用spritejs的方法变成sprite对象，然后清空原生的layer？这样的话我就遇到一个问题，请问getImageData 获取的 ImageData对象能不能直接和base64或路径一样，变成一个srpite 对象？

**Comment by akira-cn** [comment]
你直接用base64创建一个img标签，然后new一个sprite，把这个image作为sprite的texture属性就行了
