### ISSUE TITLE
能完善文档吗？

### ISSUE THREAD

**Issue by kiinlam** [spritejs/spritejs#7]
感觉目前的文档还不够详细，像Layer就没具体介绍。
然后是API文档，也是很简陋，可以的话增加点示例代码吧，而且还没有中文版的。

**Comment by akira-cn** [comment]
是的，文档会补充完整的

Layer的用法分散在坐标、事件和屏幕适配各项中，回头我们汇总一下吧

API 目前只有英文文档，很快会有中文，也会有例子的~
