### ISSUE TITLE
请问如何多次执行同一组texture动画？

### ISSUE THREAD

**Issue by ggvswild** [spritejs/spritejs#70]
spritejs很赞，不过我在使用中遇到了一个问题block住了开发，求助~

**预期目标**：在每次点击【点击播放】按钮时，都能够完整执行一次切换texture的动画

**问题描述**：仅**首次点击**后可以正常执行动画，但是此后的点击**不再**渲染动画

> 简化的case:

```javascript
class App extends Component {
    constructor() {
        super();

        this.sprite = null;

        this.onPlay = this.onPlay.bind(this);
    }
    componentDidMount() {
        this.init();
    }

    /**
     * 初始化动画
     */
    init = () => {
        const scene = new Scene('#container', {
            viewport: ['auto', 'auto'],
            resolution: [750, 1254],
        });

        const layer = this.layer = scene.layer();

        this.sprite = new Sprite();

        this.sprite.attr({ anchor: [0, 0], pos: [0, 0], size: [750, 1254], });

        layer.append(this.sprite);
    }

    /**
     * 播放动画
     */
    async onPlay() {
        // 事先缓存的img列表，试图通过切换图片播放一组动画
        const { imgs } = this.props;

        // 纹理贴图
        const keyframes = imgs.map((item) => { return { textures: item } });

        // 播放配置项
        const option = { duration: 3000, iterations: 1, easing: 'linear', fill: 'both' }

        // 执行动画
        await this.sprite.animate(keyframes, option).finished;
    }

    render() {
        return (
            <div className="animation-btn" onClick={this.onPlay}>【点击播放】</div>
        )
    }
}
```

**Comment by akira-cn** [comment]
动画播放应该没问题，你可以看[这个例子](https://code.h5jun.com/xopin/edit?js,output)

你这里的问题可能是，你的onPlay是个异步方法，你再次点击播放的时候是否前一次动画未结束？

```js
class App extends Component {
    constructor() {
        super();

        this.sprite = null;
        this.animation = null;

        this.onPlay = this.onPlay.bind(this);
    }
    componentDidMount() {
        this.init();
    }

    /**
     * 初始化动画
     */
    init = () => {
        const scene = new Scene('#container', {
            viewport: ['auto', 'auto'],
            resolution: [750, 1254],
        });

        const layer = this.layer = scene.layer();

        this.sprite = new Sprite();

        this.sprite.attr({ anchor: [0, 0], pos: [0, 0], size: [750, 1254], });

        layer.append(this.sprite);
    }

    /**
     * 播放动画
     */
    onPlay() {
        if(this.animation) this.animation.cancel(); // 如果上一次动画还没结束，取消动画

        // 事先缓存的img列表，试图通过切换图片播放一组动画
        const { imgs } = this.props;

        // 纹理贴图
        const keyframes = imgs.map((item) => { return { textures: item } });

        // 播放配置项
        const option = { duration: 3000, iterations: 1, easing: 'linear', fill: 'both' }

        // 执行动画
       this.animation = this.sprite.animate(keyframes, option);
       this.animation.finished.then(() => this.animation = null);
    }

    render() {
        return (
            <div className="animation-btn" onClick={this.onPlay}>【点击播放】</div>
        )
    }
}
```

你试试看这样是否没问题，如果还有问题，麻烦你把这个case完整地贴到codepen上，把codepen地址发过来，这样我们可以帮你快速定位和解决问题。

谢谢

**Comment by ggvswild** [comment]
> 动画播放应该没问题，你可以看[这个例子](https://code.h5jun.com/xopin/edit?js,output)
> 
> 你这里的问题可能是，你的onPlay是个异步方法，你再次点击播放的时候是否前一次动画未结束？
> 
> ```js
> class App extends Component {
>     constructor() {
>         super();
> 
>         this.sprite = null;
>         this.animation = null;
> 
>         this.onPlay = this.onPlay.bind(this);
>     }
>     componentDidMount() {
>         this.init();
>     }
> 
>     /**
>      * 初始化动画
>      */
>     init = () => {
>         const scene = new Scene('#container', {
>             viewport: ['auto', 'auto'],
>             resolution: [750, 1254],
>         });
> 
>         const layer = this.layer = scene.layer();
> 
>         this.sprite = new Sprite();
> 
>         this.sprite.attr({ anchor: [0, 0], pos: [0, 0], size: [750, 1254], });
> 
>         layer.append(this.sprite);
>     }
> 
>     /**
>      * 播放动画
>      */
>     onPlay() {
>         if(this.animation) this.animation.cancel(); // 如果上一次动画还没结束，取消动画
> 
>         // 事先缓存的img列表，试图通过切换图片播放一组动画
>         const { imgs } = this.props;
> 
>         // 纹理贴图
>         const keyframes = imgs.map((item) => { return { textures: item } });
> 
>         // 播放配置项
>         const option = { duration: 3000, iterations: 1, easing: 'linear', fill: 'both' }
> 
>         // 执行动画
>        this.animation = this.sprite.animate(keyframes, option);
>        this.animation.finished.then(() => this.animation = null);
>     }
> 
>     render() {
>         return (
>             <div className="animation-btn" onClick={this.onPlay}>【点击播放】</div>
>         )
>     }
> }
> ```
> 
> 你试试看这样是否没问题，如果还有问题，麻烦你把这个case完整地贴到codepen上，把codepen地址发过来，这样我们可以帮你快速定位和解决问题。
> 
> 谢谢

---

十分感谢！

不过上面的方案仍未能解决，简单编辑了一个case如下：
* [https://codepen.io/wesky/pen/EOdjxG](https://codepen.io/wesky/pen/EOdjxG)

希望能帮助定位~

**Comment by ggvswild** [comment]
十分感谢！

不过上面的方案仍未能解决，简单编辑了一个case如下：

[https://codepen.io/wesky/pen/EOdjxG](https://codepen.io/wesky/pen/EOdjxG)
希望能帮助定位~

**Comment by akira-cn** [comment]
感谢提供case，问题已经修复
