### ISSUE TITLE
文档有严重的内存泄漏

### ISSUE THREAD

**Issue by LuckyJoker** [spritejs/spritejs#71]
问题：内存泄漏，CPU占用率高
复现：[sprite文档](http://spritejs.org/#/zh-cn/index)，在文档左侧的目录随便多点几个栏目，然后等一会，内存占用就会飙到1G以上，并且CPU使用率也居高不下。

**Comment by akira-cn** [comment]
这个是因为文档是docsify的，是个SPA的，不会刷新页面，直接运行的实例太多了

而且因为页面切换直接DOM的canvas元素，这样自动销毁是不能保证完全回收资源的，这块等后面再优化一下。

如果把例子放到沙箱里，比如用codepen，就会好很多。
