### ISSUE TITLE
问题反馈: update事件回调会随着播放次数不断累积(即使相同的progress)

### ISSUE THREAD

**Issue by ggvswild** [spritejs/spritejs#72]
感谢spritejs带来的良好开发体验~ 这里反馈一个问题：

> 需求简介
- 尝试通过监听`update`事件获取动画播放进度，针对其中的某个进度`progress`执行特定的回调

> 预期目标
- 每次点击播放时，对于相同的`progress`只执行1次回调

> 问题描述
- 每次点击播放时，对于相同的`progress`，`update`事件回调会累计重复执行：

例如：
- 第1次点击播放按钮，每个progress执行1次；
- 第2次点击播放按钮，每个progress执行2次；
- 第3次点击播放按钮，每个progress执行3次；
...
（调用次数随着播放次数不断累积；[示意图](https://note.youdao.com/yws/public/resource/7f0478e53ebc942835a039ce9d171070/xmlnote/WEBRESOURCEa9052ca7c9172c147eaa39f31d1d0940/67471)）

**codepen**详见：
[https://codepen.io/wesky/full/EOdjxG/](https://codepen.io/wesky/full/EOdjxG/)

希望能获得帮助~

**Comment by akira-cn** [comment]
因为你的代码每次点击play都注册了一遍update呀，这样当然会变成多个。

你应该把注册事件放在init里面注册一次就行了。

代码这样修改：[CodePen](https://codepen.io/akira-cn/pen/JeqVZP?editors=0010)

**Comment by ggvswild** [comment]
原来如此。十分感谢！
