### ISSUE TITLE
部分机型引入 spritejs.min.js 报错

### ISSUE THREAD

**Issue by ggvswild** [spritejs/spritejs#73]
【问题描述】
- 当前版本的`spritejs`在部分机型上运行直接报错：

【复现方法】
```javascript
// 仅仅引入该依赖，在部分机型上立即报错白屏了
import {Scene, Sprite} from 'spritejs/dist/spritejs.min.js';
....
```

【报错信息】
`TypeError: Cannot redefine property: name`

【相关机型】
- vivo x7Plus (Android 5.1.1）
- vivo x6sa （Android 5.1.1)
- oppo R831（Android 4.3）

---

已尝试单独打包并Babel处理，未果。不知道是否由打包方式引起。

求助~

**Comment by ggvswild** [comment]
问题路径：
`node_modules/spritejs/dist/spritejs.js` 

第**6316**行的方法`_createElementDescriptor`中，尝试在问题机型中捕获异常：

```javascript
  try {
      Object.defineProperty(def.value, "name", {
        value: _typeof(key) === "symbol" ? "" : key,
        configurable: true
      });
    } catch(e) {
       // TypeError: Cannot redefine property: name
        alert('==> ' + e)
    }
```
会弹出`TypeError: Cannot redefine property: name`的报错（似乎主要在 5.x版本的vivo&&oppo机型）

**Comment by akira-cn** [comment]
我报告了一个bug给babel，一会先手工修复一下

https://github.com/babel/babel/issues/9234

明天你可以验证一下是否OK啦

**Comment by ggvswild** [comment]
问题顺利解决啦。

十分感谢！
