### ISSUE TITLE
unknown Statement of type "ClassDeclaration"

### ISSUE THREAD

**Issue by 81777268** [spritejs/spritejs#77]
当创建新Sprite时，一旦使用如  class Block extends Sprite 这样的语法就会报错
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: unknown Statement of type "ClassDeclaration"
    at Array.forEach (<anonymous>)

看起来和babel不兼容的样子，请问这个什么处理方式吗？
谢谢

**Comment by akira-cn** [comment]
请问你用的babel版本是什么？spritejs已经升级到babel7了。如果你用旧版本的babel，你可以在webpack中设置

```
resolve: {
    alias : {
        spritejs: 'spritejs/dist/spritejs.js'
    }
}
```

这样使用编译后的spritejs版本应该就可以了。
