### ISSUE TITLE
请问能否获取字体轮廓坐标？

### ISSUE THREAD

**Issue by lijialiang** [spritejs/spritejs#80]
P5js 有一个功能，[获取字体轮廓上的坐标点](https://p5js.org/reference/#/p5.Font/textToPoints)

发现很多 canvas 绘图框架都没有，请问 spritejs 有类似功能么？看文档貌似没有发现到。

**Comment by akira-cn** [comment]
这还真没有……我研究下这个

**Comment by huzunjie** [comment]
p5js的字体轮廓提取也是使用的 [opentype.js](https://github.com/opentypejs/opentype.js) ，通过字体文件解析拿到文本路径。

 SpriteJS 结合使用完全没问题，参见示例： https://code.h5jun.com/kana
