### ISSUE TITLE
Layer 和 Scene 的设计意图以及多 Layer 和 Scene 的使用场景

### ISSUE THREAD

**Issue by MwumLi** [spritejs/spritejs#81]
文档中只对 Scene 和 Layer 有简单的介绍  
 Scene 的介绍:  
> SpriteJS创建场景Scene，利用它来管理Layer，派发事件，实现屏幕适配

Layer 的介绍:  
> SpriteJS里，一个Layer对象对应一个Canvas实例。

对 Layer 和 Scene 的设计意图还是不太清楚,  而 Layer 是可以在创建时设置 id, 否则就用默认的, 那么什么场景下会用到多 Layer 和 Scene ?

**Comment by akira-cn** [comment]
两个Layer在游戏开发中比较常见，一般定义一个前景Layer，一个背景Layer，把不太需要刷新的元素绘制在背景Layer上，这样就可以不用频繁刷新。

多个Scene的话，如果在一个页面上有多个地方需要用spritejs渲染，就有可能用到。

**Comment by MwumLi** [comment]
多谢
