### ISSUE TITLE
Can I use it to capture the browser screen ? 

### ISSUE THREAD

**Issue by TryRaymond** [spritejs/spritejs#83]
html2canvas doesn't fulfill all my needs ( screen capture ),

But spritejs is powerful , Can it capture browser  screens generated by dynamic elements  ? 

What materials can I learn from (Both Chinese and English are acceptable) ?

**Comment by akira-cn** [comment]
html2canvas有哪些情况下不能满足需求？因为SpriteJS的定位和html2canvas不太一样，它不是处理DOM的，所以有些布局和属性可能不支持，当然你可以扩展它，SpriteJS支持自定义布局和扩展属性，但是这需要很大的工作量。

我还是建议可以看一下html2canvas有问题的case在哪里，看看能不能修改。

当然你可以尝试用SpriteJS看看能不能实现，如果有时间的话，我感觉应该是可以的。

**Comment by plqin-xiaohao** [comment]
> html2canvas有哪些情况下不能满足需求？因为SpriteJS的定位和html2canvas不太一样，它不是处理DOM的，所以有些布局和属性可能不支持，当然你可以扩展它，SpriteJS支持自定义布局和扩展属性，但是这需要很大的工作量。
> 
> 我还是建议可以看一下html2canvas有问题的case在哪里，看看能不能修改。
> 
> 当然你可以尝试用SpriteJS看看能不能实现，如果有时间的话，我感觉应该是可以的。

👍 👍
