### ISSUE TITLE
mousemove事件坐标问题

### ISSUE THREAD

**Issue by yky5188** [spritejs/spritejs#85]
在mousemove事件中，出现evt.x 和 originalX 不对应的问题
<img width="362" alt="wx20190226-223551 2x" src="https://user-images.githubusercontent.com/37803290/53420781-65e9f100-3a17-11e9-8eff-85f196bf8ea0.png">

**Comment by akira-cn** [comment]
originalX和originalY与x、y本来就可以不同，x、y是相对于layer的，也就是相对于canvas画布坐标的。originalX和originalY是相对于浏览器的。

layerX和originalX不相同，layerY和originalY相同，这种情况出现可能是你的viewport和resolution比例不一样。

**Comment by yky5188** [comment]
多谢，我试一下，这种情况只发生在dom初始化的时候，有点奇怪

**Comment by yky5188** [comment]
确实是因为viewport和resolution比例不一样导致的，每次初始化都相差15px，没找出原因，so加了判断强制修改resolution的width
