### ISSUE TITLE
编译报错/node_modules/spritejs/dist/spritejs.es6.js

### ISSUE THREAD

**Issue by linjc** [spritejs/spritejs#86]
/Users/linjinchun/node_modules/spritejs/dist/spritejs.es6.js
Module parse failed: Unexpected token (3907:11)
You may need an appropriate loader to handle this file type.
| }
|
| return { ...elementDescriptor,
|
| finisher(klass) {

**Comment by akira-cn** [comment]
如果从 spritejs.es6.js 编译，需要babel插件 @babel/plugin-proposal-class-properties
如果你是 webpack 打包，可以配置一下 alias: {spritejs: 'spritejs/dist/spritejs.js'}

或者你可以直接使用编译后的版本

```js
const spritejs = require('spritejs/dist/spritejs.js');
```
