### ISSUE TITLE
怎么支持 typescript？

### ISSUE THREAD

**Issue by weineel** [spritejs/spritejs#88]
webpack 打包，配置了 alias: {spritejs: 'spritejs/dist/spritejs.js'}

```js
import {
  Scene, Label, Sprite, Path, Group,
} from 'spritejs'
```

![image](https://user-images.githubusercontent.com/13328625/55055235-5b198f00-509d-11e9-8806-5ad14ad607ef.png)

**Comment by akira-cn** [comment]
这个已经解决了
