### ISSUE TITLE
有没有spritejs案例展示的？

### ISSUE THREAD

**Issue by peade** [spritejs/spritejs#89]
网上查资料，用spritejs做的东西，案例很少。
有没有专门展示spritejs作品的网站？想多学习这个的用法。

**Comment by akira-cn** [comment]
官网上有提供范例展示： http://spritejs.org/demo/

**Comment by peade** [comment]
> 官网上有提供范例展示： http://spritejs.org/demo/

谢谢，我之前没注意到，还以为一直是一个例子。
另外，网上有交流spritejs学习使用的qq群之类的么？我没搜着
