### ISSUE TITLE
如何只编译Label和animate部分？

### ISSUE THREAD

**Issue by jayter2** [spritejs/spritejs#91]
最近用canvas写一系列效果简直不要太麻烦!找框架时发现了spritejs，很感谢团队的努力，现在对spritejs爱不释手。包比较大如果放在终端硬件资源很吃紧，我尝试只编译使用Label和animate部分失败，不知是否可以单独只使用这2个部分？

**Comment by akira-cn** [comment]
只编译Label和animate是可以的，但是现在稍微有一点点麻烦

首先你fork一下 [sprite-core](https://github.com/spritejs/sprite-core) 这个项目

在这里面添加一个 `src/index.xxx.js` 文件

内容如下

```js
import {Effects, Easings, Timeline} from 'sprite-animator';
import * as math from 'sprite-math';
import * as utils from './utils';
import BaseSprite from './core/basesprite';
import Label from './core/label';
import Layer from './core/layer';
import BaseNode from './core/basenode';

// load modules
import './modules/animation';

const Color = utils.Color;

export {
  utils,
  math,
  BaseNode,
  BaseSprite,
  Label,
  Layer,
  Effects,
  Easings,
  Timeline,
  Color,
};
```

然后你把spritejs的webpack中sprite-core的alias设置成这个文件，然后在spritejs中也创建index.xxx.js，把这个文件作为入口加载需要的模块

**Comment by jayter2** [comment]
非常感谢
