### ISSUE TITLE
鼠标移动到热点位置，怎么显示成手型指针(cursor: pointer)？

### ISSUE THREAD

**Issue by weineel** [spritejs/spritejs#93]
查看了 [demo buttons]L(http://spritejs.org/demo/#buttons) 的实现，感觉有点hack，会实现通过 attr 的方式设置某个元素为 `cursor: pointer`吗？

**Comment by akira-cn** [comment]
出于性能考虑，不能支持cursor:pointer这样的属性，否则的话，每次鼠标移动都要做碰撞检查。

所以还是只能通过mouseenter、mouseleave来自己改变canvas.style.cursor了。
