### ISSUE TITLE
编译后运行报错:Cannot assign to read only property 'exports' of object 

### ISSUE THREAD

**Issue by jayter2** [spritejs/spritejs#94]
node8.15.1 环境,npm run build 打包编译后，使用dist目录下任意文件时报错：
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

**Comment by akira-cn** [comment]
如果是2.28.0之前的老版本，用webpack编译的时候配置一下
```json
{
    alias: {spritejs: 'spritejs/dist/spritejs.js'}
}
```

如果是2.28.0之后的新版本，应该这个问题已经修复了。
