### ISSUE TITLE
texture 动画：向 group 添加 sprite 之后立即执行 `sprite.animate` 出现的怪异问题

### ISSUE THREAD

**Issue by AngusFu** [spritejs/spritejs#95]
## 重现

这里是[例子](https://code.h5jun.com/pozop/edit?html,css,js,output)。

## 场景
简单说明一下目的：我需要创建许多包含一个 label 和一个 sprite 的 Group 对象（sprite 在创建时会立即调用 animate），然后这些对象统一交给另外一个 Group 对象管理。

## 出现的问题

可以直接看 [demo](https://code.h5jun.com/pozop/edit?html,css,js,output)。其中有三个 Bird Class（Bird1, Bird2, Bird3。其中，Bird1 是有问题的；Bird2 和 Bird3 仅仅是对 Bird1 做了微调，表现正常。

**Comment by akira-cn** [comment]
这是因为group添加到layer中时，子元素的connect不会被调用，而animation是在元素的connect中激活的。这里的策略可能需要调整一下了。

**Comment by akira-cn** [comment]
v2依然有问题，v3修改了机制，已经解决这个问题
