### ISSUE TITLE
ie及edg浏览器都不行

### ISSUE THREAD

**Issue by CheiZhei** [spritejs/spritejs#96]
npm版本，ie和edg浏览器运行都不行，是需要自己加载polyfill嘛

**Comment by akira-cn** [comment]
因为spritejs我们主要用来做可视化的项目，所以没在IE下测过，具体是什么原因报错，能提供错误信息吗？

**Comment by CheiZhei** [comment]
Symbol未定义

**Comment by akira-cn** [comment]
https://github.com/babel/babel-preset-env/issues/203 你可以看一下这个

因为spritejs里使用Symbol来定义私有属性，这个IE下是需要polyfill的

**Comment by weineel** [comment]
在sprite 元素(比如Group)上监听 ‘mouseenter 事件，当鼠标进入时报如下错误：`Object doesn't support property or method 'isPointInStroke'`
![image](https://user-images.githubusercontent.com/13328625/56340722-57cd7b00-61e5-11e9-9233-fad5d6cbb085.png)

环境：`Microsoft Edge 44.17763.1.0`
